### ISSUE TITLE
Day animations stopped working

### ISSUE THREAD

**Issue by tiemevanveen** [Mozharovsky/CVCalendar#10]
Hi Euegene,

I noticed that the little dots are not animating down any more (upon day selection) in the demo app. Maybe your refactoring broke something?

Tieme

**Comment by Mozharovsky** [comment]
Hello @tiemevanveen, 

In a few previous changes I've added more features for customization. Now you can easily turn **dotMarker**'s moving on and off. Take a look at **[this page](https://github.com/Mozharovsky/CVCalendar/wiki/CVCalendarViewDelegate)**. (The last row)

And ViewController in Demo project turns this feature off. 

```swift
    func dotMarker(shouldMoveOnHighlightingOnDayView dayView: CVCalendarDayView) -> Bool {
        return false
    }
```

**Comment by tiemevanveen** [comment]
Got it, thanks. I didn't found the wiki yet...
