### ISSUE TITLE
now working with orientation changes.

### ISSUE THREAD

**Issue by prabhatk** [Mozharovsky/CVCalendar#102]
Hello,
When we use autolayout to rotate device and use this controller view with the scroll view or table view cell it skips the vertical scroll of scrollview/tableView.

it doesn't work in landscape mode.

**Comment by Mozharovsky** [comment]
Hello @prabhatk, 

Thank you for reporting the orientation issue. 

I'll add size re-calculation in the nearest maintenance. Keep watching! 

Regards, 
Eugene

**Comment by break2k** [comment]
Hello,

any progress here ? I would also help if you need any help.

:wave:

**Comment by r3mus** [comment]
Any word on this? Definitely an unpleasant experience on landscape. Should be a relatively easy fix though - if you can suggest a course of action I'd be happy to take a look.

**Comment by blwinters** [comment]
Not sure whether this or issue 77 is active, but it would be nice to see a fix for this, especially with iOS 9 pushing us to support all orientations.

**Comment by elsesiy** [comment]
@blwinters Our issue list is quite long, but we're definitely working on it!

**Comment by DennisDreissen** [comment]
This is definitely an important issue. I'm currently working on iPad support for my app, but the calendar days view doesn't resize properly.

**Comment by brandonscript** [comment]
Made some progress today looking inside `calendarView.commitCalendarViewUpdate()`. By adding in `contentController.view.layoutIfNeeded()`, it at least updates the current bounds of the view. Setting `calendarView.validated` public and then to false inside a rotation event now gets the frames of the day and week views updating properly; the only problem is that the day selector circles get totally goofed and start re-drawing all over the place. Going to continue playing around to see if I can't figure out a cleaner solution.

**Comment by mazurio** [comment]
@brandonscript Have you figured out how to refresh the circles? I added validated too but the circles bug is worse than without validated.

**Comment by brandonscript** [comment]
Yeah, I couldn't get it to work at all unfortunately. Given up for the time being.

**Comment by mazurio** [comment]
Hi @brandonscript , I have managed to fix it yesterday with this commmit:
- https://github.com/mazurio/bodyweight-fitness-ios/commit/febbdbb4be22c696f2174a5c596f66bec56536eb

it's very hacky but it works for now 👍

**Comment by coryhymel** [comment]
@mazurio I'm getting a crash on this cast: 
`let weekContentViewController = self.calendarView.contentController as! CVCalendarWeekContentViewController`

any thoughts??

**Comment by elsesiy** [comment]
Fixed in #384
