### ISSUE TITLE
No longer adjust height to hide/show additional dates

### ISSUE THREAD

**Issue by hipwelljo** [Mozharovsky/CVCalendar#104]
I would like to request a change in behavior. Instead of adjusting the height to hide/show an additional row of dates, it should remain at the max height it needs to in order to ensure all dates can be shown. The hiding and revealing of icons is poor when swiping to the different months.

**Comment by Mozharovsky** [comment]
Hello @hipwelljo, 

Thank you for the reported issue. 

I've updated the [develop](https://github.com/Mozharovsky/CVCalendar/tree/develop) branch, so this problem should be fixed now. Please take a look at the Demo project with its updated storyboard. Also there is a new method for setting the animation on calendar resizing. Check it out in a ViewController.

In case of any issues let me know. If it works, please close the issue. 

Regards, 
Eugene

**Comment by hipwelljo** [comment]
Excellent work! It does exactly what I want when I set shouldAnimateResizing to false. Loving this calendar. Thanks for working on that so quickly!
