### ISSUE TITLE
Compilation errors when adding as a pod

### ISSUE THREAD

**Issue by nspassov** [Mozharovsky/CVCalendar#105]
Hi Eugene,

First of all, the Calendar looks really great! However, I am getting compilation errors when adding it as a pod to an Obj-C project (using Xcode 6.4 btw).

Lots of `Must call a designated initializer of the superclass` errors on the UIView subclasses. Would really like to integrate CVCalendar into a project but I would rather it was written in Obj-C as I do not think the Swift language is (yet) a good choice for writing reusable components.

**Comment by Mozharovsky** [comment]
Hello @nspassov, 

Thank you for using CVCalendar. 

Actually, there is an outdated version provided by CocoaPods. I'm going to update it soon. 

Regards, 
Eugene

**Comment by mdrewitt** [comment]
Hey @Mozharovsky,

Just wondering if there is any update on getting the latest up on CocoaPods.  It would be nice to be able to continue managing it through there.

Thanks,
mdrewitt

**Comment by tobyfan1980** [comment]
same issue. When I add it to my swift project using CocoaPods, it gives 10 Compiler error and 20 warning.

**Comment by Mozharovsky** [comment]
Resolved #111
