### ISSUE TITLE
Compile Errors

### ISSUE THREAD

**Issue by danielknsg** [Mozharovsky/CVCalendar#106]
Hi All,

I'm facing issues while trying to import the CVCalendar files into my project.
It comes up with a lot of compile errors.
Not sure if I did something wrong, but just copied the folder into my project.

Any hints what i can do?

XCode Version is 6.2

Attached a screenshot.

Thanks and best regards,
Daniel
![cvcal_issue](https://cloud.githubusercontent.com/assets/13732715/9174024/3a5baa52-3fb0-11e5-8d75-ade3c37f4d29.jpg)

**Comment by ingridqi** [comment]
This might be a problem with the Swift version. I believe Xcode 6.2 supports Swift 1.1, but the source code supports Swift 1.2.

**Comment by danielknsg** [comment]
Thanks for your fast response.
It was really a problem with my old Swift version.
