### ISSUE TITLE
[1.1.0] CocoaPods integration 

### ISSUE THREAD

**Issue by Mozharovsky** [Mozharovsky/CVCalendar#111]
Update the project to support CocoaPods integration. 

**Related issues**: #6 #25 #67 #105

**Comment by Mozharovsky** [comment]
Validated a new pod spec and added it to the trunk 6893d93f8d89773d1451f82f278f24ff63e73fa6.

**Comment by Mozharovsky** [comment]
Alive on [CocoaPods](https://cocoapods.org/pods/CVCalendar)!

**Comment by tobyfan1980** [comment]
I am new to cocoapods.  When I follow you guides I got compile error.  
![screen shot 2015-08-28 at 10 41 22 am](https://cloud.githubusercontent.com/assets/11427591/9553076/8b9d8736-4d71-11e5-9ea8-54f4a4082082.png)

Even I explicitly import, it shows no such module.  I have pod version 0.38.2.  But no issue with some other library I found in CocoaPods.org

**Comment by Mozharovsky** [comment]
Try to import CVCalendar. :)

**Comment by tobyfan1980** [comment]
This works. I see I should import the framework name. Thanks.

**Comment by skmani** [comment]
i am getting a error "No such module 'CVCalendar'" after import CVCalendar, Any suggesion

**Comment by ira-ira** [comment]
@skmani this is Xcode bug, try to build, this will fix your problem
