### ISSUE TITLE
Swift 2.0 support

### ISSUE THREAD

**Issue by ratkins** [Mozharovsky/CVCalendar#113]
I notice there's no Swift-2.0 branch for CVCalendar.

Has Swift 2.0 support been considered? What is the migration strategy?

(Note, "Pull Requests gratefully accepted" is a valid response to this issue :-)

**Comment by orlandoamorim** [comment]
+1

**Comment by nexon** [comment]
+1

**Comment by avvensis** [comment]
+1

**Comment by bjaskj** [comment]
Need this as well please :+1:

**Comment by avicooper1** [comment]
I see that a new release for Swift 2 was posted, but the pod does not seem to be available. Is this possible?

**Comment by derdida** [comment]
+1

**Comment by dasoga** [comment]
For this moment, I opened CVCalendar folder in my folder project with pods and I updated the files manually. I hope can help while is update on cocoapods

**Comment by elsesiy** [comment]
@dasoga That's actually not necessary and not the way to go, you should specify the repository location in the podfile instead until the podspec is being updated, i.e.
`pod 'CVCalendar', :git => 'https://github.com/Mozharovsky/CVCalendar', :branch => 'master'`

**Comment by dasoga** [comment]
@elsesiy thanks dude, i didn't know that!

**Comment by erikjalevik** [comment]
I just cloned the master branch, which according to the log, should have been converted to Swift 2.0, but still Xcode asks me if I want to convert to latest Swift syntax and the compiler reports a bunch of error.

What's the status here?

**Comment by elsesiy** [comment]
@erikjalevik The master branch supports Swift 2.0, so how did you clone the branch? Are you using cocoapods? If so please have it point to the git repository as stated above, since the podspec hasn't been updated yet. Otherwise please have a look at  https://github.com/Mozharovsky/CVCalendar/pull/115#issuecomment-142946245

**Comment by derdida** [comment]
Are this still errors in the 2.0 version? I am unable to compile with Swift 2.0, but it seems like that is the latest version. So still in development?

**Comment by elsesiy** [comment]
@derdida Swift 2 is officially supported by now. I already mentioned several times, that the pod spec hasn't been updated yet, so you have to specify the repository as mentioned above. If you're not using cocoapods please make sure you've added the sources to compile sources in build settings. If you've further remarks, please let us know and specify as specific as possible what the exact problem is.

**Comment by dwightwatson** [comment]
Pinging @Mozharovsky would you be able to update the podspec to match the `1.2.0` release? Also, you  might want to pull the current `1.2.0` release on GitHub for [this repos releases](https://github.com/Mozharovsky/CVCalendar/releases).

**Comment by elsesiy** [comment]
@dwightwatson Thanks for contributing and helping others to use this library (https://github.com/Mozharovsky/CVCalendar/issues/123)
Since this is a recurring issue, I have created a PR with the updated Podspec rightaway. Hopefully @Mozharovsky will merge it soon!

**Comment by Mozharovsky** [comment]
Hello guys! Version 1.2.6 has been pushed into CocoaPods, check this out!

**Comment by poppindouble** [comment]
Hello, yes, the 1.2.6 works for me, however still some warnings are presented when compiling, is there any method to get rid of it?

**Comment by elsesiy** [comment]
@poppindouble We'll take care of it soon, just ignore them :+1:

**Comment by elsesiy** [comment]
@poppindouble If you're on the master branch, the latest commit should've cleaned all warnings! -> Close

**Comment by poppindouble** [comment]
Thanks!!

**Comment by pradeepkumari** [comment]
how to get lastdate of a month from my input date.Ex. input: 24-9-16 output: 30-9-16
