### ISSUE TITLE
Marking dots

### ISSUE THREAD

**Issue by vichiodo** [Mozharovsky/CVCalendar#114]
Hi, do you have any documentation of how to mark dots on specific dates in the CVCalendar?

**Comment by sohilmemon** [comment]
To mark dots on specific date use this metthod:

func dotMarker(shouldShowOnDayView dayView: CVCalendarDayView) -> Bool {

     let day = dayView.date.day //To get the Day from the Calender
    
     //Check our specific date with the dates on calender
     if day == CVDate(date: NSDate).day{
          return true
     } 
    return false
}

**Comment by shan199105** [comment]
Hi, is there a method for me to call in order to redraw all the dot marker?

**Comment by sohilmemon** [comment]
Yes, you can reload the CVCalendar in many ways and with that `dotMarker` will also get reload.

In, `CVCalendarDayView -> reloadContent()`
In, `CVCalendarMonthView -> reloadMonthViews()`
In, CVCalendarWeekView -> reloadWeekViws()`

Hope, you can find it and solve your issue.

Thanks.

**Comment by camposmandy** [comment]
Sorry but how can I reload the calendar? I'm trying what you said but it's not working.

**Comment by mechdon** [comment]
I too am trying to refresh/reload the dot markers. I tried those reload methods(reloadContent, reloadMonthViews), but they don't seem to work. When I try to call these methods, I'm met with "unexpectedly found nil while unwrapping an Optional value" error.

**Comment by elsesiy** [comment]
If the issue still occurs, I'm gonna reopen this issue, but closed for now. Thanks!

**Comment by matthewmayer** [comment]
this worked for me:
````
 if let cc = calendarView.contentController as? CVCalendarMonthContentViewController {
            cc.refreshPresentedMonth()
        }
````

**Comment by hemanth2k13** [comment]
App Crashing when above method returns 'true'. It says found nil while unwrapping optional value.

**Comment by makomori** [comment]
@matthewmayer Your solution worked for me. Thanks a lot!
