### ISSUE TITLE
Select Date Range

### ISSUE THREAD

**Issue by maail** [Mozharovsky/CVCalendar#12]
Not much of an issue but a request. :)

Would be great if I can select a date range and get those selected dates.

**Comment by Mozharovsky** [comment]
Hello @maail, 

The only thing coming to my mind is dealing with long pressure touches. As soon as CVCalendar detects a long pressure touch it immediately starts selecting day views in a chain. 

I'll try to create a prototype in the near maintenance work this weekend. 

Regards, 
Eugene

**Comment by maail** [comment]
Hi @Mozharovsky,

What I had in mind was to select one date (as it is now). Then while having this date selected, select another date. So then I can get the selected dates.

**Comment by Mozharovsky** [comment]
Hello @maail, 

I'm currently preparing CVCalendar for a new release. So I would like to make sure I understand the feature you've suggested well enough. I think of how to invoke range day view selection. It can be presented statically or dynamically. What I mean is that you can either select day views range only or you can select both range and a single day view. 

Let me know how you think would be better. 

Thank you in advance. 

Regards, 
Eugene

**Comment by maail** [comment]
Hi Eugene,




I'm currently looking for date range. Select one date and then select another date. So from Start Date to End Date the dates will be highlighted to show the user that these date range has been selected.




I think you can give the option for both range and one day when initializing the function.




Thanks,

Maail



—
Regards,
Mohamed Maail Rasheed
Application Developer

Portfolio: http://thirdgene.com

**Comment by yaronlevi** [comment]
Also, in this notion, can you please add a way to select multiple dates , but not a range. For example, these 3 dates will be selected and blue circle around them:
27/03/2015
02/07/2015
11/04/2014

It will be a great feature and will help a lot (:

**Comment by justdan0227** [comment]
Hey @Eugene, was wondering if you had implemented the call back based on a range.  I see that I'm getting message in the log of: 
```
Received start of range selection.
Received end of range selection.
Received start of range selection.
Received change of range selection.
Received change of range selection.
Received end of range selection.
```

and didn't know if that information was then sent back to us?

**Comment by RIju912** [comment]
How to get the range of the selected dates.?

**Comment by elsesiy** [comment]
Fixed in https://github.com/Mozharovsky/CVCalendar/commit/89b1e42486a4bfea938211397aee902512981cd1

**Comment by zocario** [comment]
@elsesiy Is there any release planned soon that will make this feature available?

**Comment by elsesiy** [comment]
@zocario I'll see if I can release a new version by the end of this week.
