### ISSUE TITLE
Not working on Swift 2.0

### ISSUE THREAD

**Issue by javierdac** [Mozharovsky/CVCalendar#123]
if i use it with cocoapods 

pod 'CVCalendar', '~> 1.1.4'

is not working with Swift 2.0

**Comment by dwightwatson** [comment]
See #113. This pod should be compatible with Swift 2 in release `1.2.0` but that hasn't been tagged properly yet.

In the meantime you can reference the `master` branch of the repo which should be good to go.

    pod 'CVCalendar', :git => 'https://github.com/Mozharovsky/CVCalendar', :branch => 'master'

**Comment by javierdac** [comment]
i try that however is not working because i use use_frameworks!

**Comment by dwightwatson** [comment]
Can you post the actual error you're receiving? use_frameworks! would actually be required for this pod, rather than causing an issue.

**Comment by Mozharovsky** [comment]
It should work now! Try out 1.2.6 version!
