### ISSUE TITLE
CVCalendarview.swift errors?

### ISSUE THREAD

**Issue by DennisSnijder** [Mozharovsky/CVCalendar#126]
I am not really an IOS developer... so maybe you guys can help me out.
when including this library i get these error message on this line
 public var (weekViewSize: CGSize?, dayViewSize: CGSize?)
Expected "," before the ?

**Comment by elsesiy** [comment]
I'm sorry but what do you want to achieve?
The declaration is wrong, it must be `public var (weekViewSize, dayViewSize) : (CGSize?,CGSize?)` since this library is using swift 2!

**Comment by DennisSnijder** [comment]
@elsesiy thanks for the reply!
i got an existing app where i need to work on, the thing is i aint an swift developer.
trying to get the app working on my xcode but i get these errors.

**Comment by elsesiy** [comment]
@DennisSnijder So how can I help you with exactly? First we need to clarify if you've included everything properly so please provide me with specific information on what you've done so far. Usually including the latest version of this library doesn't cause any errors..

**Comment by Mozharovsky** [comment]
@DennisSnijder: Did you manage to integrate CVCalendar successfully?

**Comment by elsesiy** [comment]
@Mozharovsky It's been three month, I guess he should be fine otherwise he would've mentioned it again...hence closed for now.

@DennisSnijder If you've further remarks, please let us know!
