### ISSUE TITLE
Showing 1 week

### ISSUE THREAD

**Issue by martjemeyer** [Mozharovsky/CVCalendar#13]
Hey, great job on the Calendar so far!
One question, 
Is it possible to show just one week of the monthview, so I have more space to put some information under the calendar view?
Or do you plan to extend the calendar to have a separate  month/week and day view?

Henk-Martijn

**Comment by Mozharovsky** [comment]
Hello @martjemeyer, 

Thank you for the given idea. This feature will be implemented in the near maintenance planned on this weekend. 

Regard, 
Eugene

**Comment by martjemeyer** [comment]
Sounds great, looking forward to it!

**Comment by Mozharovsky** [comment]
@martjemeyer, I've just pushed the changes where I added a feature of single week construction. It is not yet completed. Just initial stuff. Try to test it in order to find bugs if any. Please let me know if you find one.

**Comment by martjemeyer** [comment]
Exactly what I meant! So far it does what it should, although I'm not really busy at this part of the app yet.
The showing days out and going to the current date functions return nil atm, but I think you are aware of that already :)
Again great job so far!

**Comment by Mozharovsky** [comment]
Indeed. There is some work left to be done. So within a few days it will work as a clock! And I still ask for testing if any bugs might be found.

**Comment by Mozharovsky** [comment]
I've pushed even more features. Now it works with the same API for both **MonthView** and **WeekView** modes. The only thing's required is testing. If there is no bugs and issues I'll merge branches and push a new library release.

**Comment by Mozharovsky** [comment]
My testing hasn't detected bugs, so I close the issue.

**Comment by eshwartm** [comment]
Hi, 

When I animate to single week view, it isn't highlighting the current date?
