### ISSUE TITLE
converting CVDate to NSDate

### ISSUE THREAD

**Issue by Sun-Sun** [Mozharovsky/CVCalendar#130]
Hello, firstly thank you for the wonderful library that you have created

I am having just one problem so far. I cannot retrieve the date in the certain format that I would like as the function to change the date is private so I cannot access it by extending CVDate. As well as that, I cannot convert CVDate to NSDate for my own convenience. I would really like to be able to change the date that I retrieve to yyyy-MM-dd to be able to send this to a database

Currently you only have 2 methods of retrieving the date and they both return custom inconvertible dates
calendarView.presentedDate.commonDescription
calendarView.presentedDate.globalDescription

**Comment by javierdac** [comment]
you can use this function to have your date in NSDate:

self.calendarView.presentedDate.convertedDate()! 


Best!

**Comment by Sun-Sun** [comment]
Thank you very much

I have not tested it yet but will get back to you if anything goes wrong

Regards
Sun Sun

**Comment by break2k** [comment]
you can close that. Works good for me

**Comment by swiftFrolov** [comment]
I have a problem, that convertedDate returns the day before that i choosed. eg: i choosed 23 of january, but convertedDate returns 2016-01-22 16:00:00 +0000
