### ISSUE TITLE
Error on version 126 (Swift 2.0)

### ISSUE THREAD

**Issue by javierdac** [Mozharovsky/CVCalendar#133]
if i set up the last version with cocoapod i get this:

2015-10-14 16:19:06.786 Mahi[36493:15592533] *** Terminating app due to uncaught exception 'NSUnknownKeyException', reason: '[<UIView 0x7fa703b02d30> setValue:forUndefinedKey:]: this class is not key value coding-compliant for the key calendarAppearanceDelegate.'

In my pod file i need to set use_frameworks! not for this library but for other i am using.. i can imagine that this could be the problem.

**Comment by elsesiy** [comment]
@javierdac Sorry for the late response. Does the issue still occur?

**Comment by javierdac** [comment]
@elsesiy yes i have the same issue:

*** Terminating app due to uncaught exception 'NSUnknownKeyException', reason: '[<UIView 0x7fbb1947a8a0> setValue:forUndefinedKey:]: this class is not key value coding-compliant for the key calendarAppearanceDelegate.'

i try also this: 

pod 'CVCalendar', :git => 'https://github.com/Mozharovsky/CVCalendar.git'

and after changing the line 259 from 
            delegate?.didSelectDayView?(dayView, animationDidFinish: false)
to 
            delegate?.didSelectDayView?(dayView)

i have this problem

*** Terminating app due to uncaught exception 'NSUnknownKeyException', reason: '[<UIView 0x7f92b58a71e0> setValue:forUndefinedKey:]: this class is not key value coding-compliant for the key calendarAppearanceDelegate.'

**Comment by elsesiy** [comment]
@javierdac Thanks for the reply. Ok so I was able to reproduce the issue. Since the master branch is under heavy development, please stick to the released versions for now. Just remove the `:git` tag and you should get the latest release (1.2.7.) which works fine!

**Comment by javierdac** [comment]
@elsesiy the version 1.2.7 from cocoapods is still not working in my project. I need to use use_frameworks! becaue otthers libraries. Did you try with it?

Best!

**Comment by elsesiy** [comment]
@javierdac Yeah I did, my sample Podfile looks as follows:
```
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
use_frameworks!

target "PodTest" do
  pod 'CVCalendar'
end
```

**Comment by javierdac** [comment]
@elsesiy 

i should do something wrong, i keep having the same error, this is an example project:

https://www.dropbox.com/s/x37lagmvsibdcmp/TestCalendar.zip?dl=0

2015-11-01 19:42:06.251 TestCalendar[12674:5568857] -[UIView commitCalendarViewUpdate]: unrecognized selector sent to instance 0x7fbd70725470
2015-11-01 19:42:06.253 TestCalendar[12674:5568857] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[UIView commitCalendarViewUpdate]: unrecognized selector sent to instance 0x7fbd70725470'

**Comment by javierdac** [comment]
hi @elsesiy did you have the chance to try it? I still having the same problem.

Thanks!

**Comment by elsesiy** [comment]
@javierdac Hi, yes I just checked and found the issue. You haven't set the classes in IB correctly, so the Module where to find those is missing. If you just go into your Storyboard and type in again the CVCalendarMenuView/CVCalendarView, the module will be set and thus the exception won't occur again. Please for the future just stick to the Demo Project, it's basically designed for preventing those mistakes.
