### ISSUE TITLE
system lang error

### ISSUE THREAD

**Issue by quattroGeko** [Mozharovsky/CVCalendar#140]
Hi,

i you are running en-us iPhone it's running fine but my iPhone is Turkish lang & component giving error on compile.

  public func weeksWithWeekdaysForMonthDate(date: NSDate) -> (weeksIn: [[Int : [Int]]], weeksOut: [[Int : [Int]]]) {
        
        let countOfWeeks = self.monthDateRange(date).countOfWeeks
!!!!!!!!!    ERR HERE--->    let totalCountOfDays = countOfWeeks * 7
        let firstMonthDateIn = self.monthDateRange(date).monthStartDate

**Comment by elsesiy** [comment]
@quattroGeko Hi, ok so I tried reproducing your issue but I can't figure it out. Region and Lang are in Turkish now, but still works fine. Can you please provide specific information on how to reproduce the problem? Thanks!

**Comment by elsesiy** [comment]
Please reopen if the problem still persists. Thanks!
