### ISSUE TITLE
Loading dates on calendar from remote JSON web service

### ISSUE THREAD

**Issue by coanag** [Mozharovsky/CVCalendar#143]
Hello, thank you for the t great library.
I was wondering if is there any suggested way to load dates from web service to a monthview, in cvcalendar?

I can across library references and issues , but I'm not sure what to do.
One ref is : https://github.com/Mozharovsky/CVCalendar/issues/80.
Lets say i have an array with month dates, which function should be used to load em to calendar?
Excuse me in advance if i missed or didn't see something from documentation or issues but need some help.

Thank you

**Comment by joelwass** [comment]
create an array of dates -> convert them into a CVDate, i can go into more detail if you want for how to do this... then once you have an array of CVDates, in the function supplementaryView(shouldDisplayOnDayView) you check to see if the dayView.date passed in the function is equal to ANY value in your CVDate array, if it is, return true. that will result in a blue circle on all of the dates you imported from the json web service

**Comment by elsesiy** [comment]
@joelwass Thanks for helping others out! Your explanation is totally correct, so I'm gonna close this issue for now. If there're any further remarks on that I'll reopen it :+1:

**Comment by joelwass** [comment]
I'll continue helping out with issues, i'm pretty deep in a project with
your pod so i know a lot about it. if you could help me with the issue i
posted, that would be greatly appreciated

**Comment by coanag** [comment]
Thank you very much

**Comment by poppindouble** [comment]
@joelwass  hello, can you tell me more details about how to create CVDate object?
I have the day, month, and year, the only thing i don't know how to get the "week" parameter. Is it the weekofMonth? Could you give me a bit more information about it? Thanks!!!!

**Comment by joelwass** [comment]
say you have a string of a date "month/day/year", let's do 2/14/2013 for example. we can then do the following to create a CVDate:
let date = "2/14/2013"
let dateFromString = date.componentsSeparatedByString("/")
let newCVDate = CVDate(day: Int(dateFromString[1])!, month: Int(dateFromString[0])!, week: ((Int(dateFromString[1])!)/7)+1, year: Int(dateFromString[2])!)

**Comment by poppindouble** [comment]
@joelwass Thanks!

**Comment by poppindouble** [comment]
@joelwass  one more question. what if I have a UISegmentedControl in my app, I want to achieve the feature like this, when the user select different segment, the calendar will show different contents, so basically i need to reload the calendar to show different content. how to achieve this features? is there any function in the library similar to tableview.reload()?  Thanks!!!!

**Comment by joelwass** [comment]
Depends what you're trying to do... there is no calendarView.reload()
function as you wish, but you can display different things based on a
segment control in some cases. Do you want to display different stuff based
on the segment for an individual day? or based on the segment, display
different days?

On Tue, Nov 3, 2015 at 10:52 AM, Shuangshuang Zhao <notifications@github.com

**Comment by poppindouble** [comment]
@joelwass  Hi, I want to achieve  based on the segment, display different days.

**Comment by poppindouble** [comment]
@joelwass also, the function dotMarker(shouldShowOnDayView dayView: CVCalendarDayView) -> Bool seems has some bugs #153

**Comment by joelwass** [comment]
unless i get a response to my quesiton about creating a dayView object form a cvdate, it isn't possible to select another dayView without tapping on it... I'll keep you updated

**Comment by poppindouble** [comment]
@joelwass  sure, thanks a lot

**Comment by coanag** [comment]
@joelwass 
Thanks for the help.
When going to next month, where do you suggest should call the function to remote web service and recalculation of calendar's events? And how to get dayView.date.day?

**Comment by joelwass** [comment]
everytime a month loads, the funciton

preliminaryView(shouldDisplayOnDayView dayView: DayView) -> Bool

you should only recalculate calendar events from the webservice as
infrequently as possible, so i wouldn't suggest calling it on everysingle
dayview.Date which may be what you're planning to do.

you should try to call the events from a web service on loading the entire
calendar view view controller and then displaying certain data on certain
days when they are loaded.

**Comment by coanag** [comment]
Im planning to call only one month's events which the user is currently seeing. I was hoping when users is swiping left or right between months, to trigger month events and load them in calendar view. From your experience with cvcalendar can you suggest an efficient way using cv's methods?

**Comment by joelwass** [comment]
a method is probably called whenever next or previous is tapped, i'd look
into that!

**Comment by thomasbaldwin** [comment]
@joelwass, the issue I'm having is that this method 
```swift
func dotMarker(shouldShowOnDayView dayView: CVCalendarDayView) -> Bool {
```
is already called when I receive my data back (so it has already returned false for every single day in the month). Is there a method I can call on the calendar that will trigger this method to be called again?

**Comment by joelwass** [comment]
there isn't at the moment, my refresh calls dayView(shouldShowOnDayView
....) but doesnt do the same for dotMarker(shouldShowOnDayView ...) try to
hack a way around it by doing something similar to my refresh method
referenced here:
https://github.com/joelwass/CVCalendar/commit/39261f1b20f8d6309cf2fe79ac56872a78c49c99

method: refreshPresentedMonth

**Comment by coanag** [comment]
didShowNextMonthView and didShowPreviousMonthView saved my day. Thank you!
Im having trouble in supplementaryView(shouldDisplayOnDayView dayView: DayView).
I've  created my cvdates array (with something like CVDates.date = CVDate(date: date)), I'm successfully showing dots with dot marker for every month i want
but i fail to show circles..
My loop inside supplementaryView as you suggested:
        for i in 0..<CVDates.count
        {
            let item = CVDates[i]
            if (item.cvdate == dayView.date )
            {
                return true
            }
        }
Am i missing something?
When compared item.cvdate.day with dayView.date.day, worked but for current month.
Could i call supplementaryView for a specific date?

**Comment by joelwass** [comment]
are you also doing the same loop within preliminaryView(shouldDisplayOnDayView dayView: DayView) -> Bool { ?

if not, try that

**Comment by coanag** [comment]
No luck, it seems that my cvdate is never equal dayView.date and seems strange because comparing dayView.date.day and dayView.date.month is working.
Is there anyway to force show a circle on calendar day?

**Comment by joelwass** [comment]
make sure your cvdate is of correct format, you can check by printing out
your cvdate array as well as printing out the dayView.date whenever the
method is called.

**Comment by joelwass** [comment]
oh i think i misunderstood. you can't compare cvdate objects, you have to
compare if your cvdate.month == dayView.date.month && cvdate.day ==
dayView.date.day && cvdate.year == dayView.date.year {
then do something
}
 etc...

**Comment by PoojaSannidhi** [comment]
@coanag were you able to do circle calendar dates based on json response if so please share the demo.i am not able find where do i need to put my json response and from where i need to call

**Comment by coanag** [comment]
@PoojaSannidhi yes its possible. Download the json response and then call dotMarker func if you want to show dots and func supplementaryView(shouldDisplayOnDayView dayView: CVCalendarDayView) -> Bool  >> for circles. In these functions loop your your events from json.
Something like:
`
            for i in 0..<monthEvents.count
            {
                let item = monthEvents[i]
                
                if (item.date?.day == dayView.date.day && item.date?.month == dayView.date.month )
                {
                    return true
                }
            }`

Its been a while since this project, so i hope it helps :)
