### ISSUE TITLE
some errors for latest version of swift

### ISSUE THREAD

**Issue by zsw12abc** [Mozharovsky/CVCalendar#149]
i just install it to my project and there are many errors in frameworks

private let YearUnit = NSCalendarUnit.CalendarUnitYear
private let MonthUnit = NSCalendarUnit.CalendarUnitMonth
private let WeekUnit = NSCalendarUnit.CalendarUnitWeekOfMonth
private let WeekOfYearUnit = NSCalendarUnit.CalendarUnitWeekOfYear
private let WeekdayUnit = NSCalendarUnit.CalendarUnitWeekday
private let DayUnit = NSCalendarUnit.CalendarUnitDay
private let AllUnits = YearUnit | MonthUnit | WeekUnit | WeekOfYearUnit | WeekdayUnit | DayUnit

// MARK: - DateUnit operators overload

public func + (lhs: DateUnit, rhs: Int) -> NSDate {
    return dateUnitOffset(lhs, rhs, { x, y in x + y })
}

public func - (lhs: DateUnit, rhs: Int) -> NSDate {
    return dateUnitOffset(lhs, rhs, { x, y in x - y })
}

public func * (lhs: DateUnit, rhs: Int) -> NSDate {
    return dateUnitOffset(lhs, rhs, { x, y in x * y })
}

public func / (lhs: DateUnit, rhs: Int) -> NSDate {
    return dateUnitOffset(lhs, rhs, { x, y in x / y })
}

public func == (lhs: DateUnit, rhs: Int) -> NSDate {
    return dateUnitOffset(lhs, rhs, { _, y in y })
}

// MARK: - NSDate operators overload

public func == (lhs: NSDate, rhs: NSDate) -> Bool {
    return compareWithOperation({ $0 == $1 }, { $0 && $1 && $2 })(lhs, rhs)
}

public func > (lhs: NSDate, rhs: NSDate) -> Bool {
    return compareWithOperation({ $0 > $1 }, { $0 || $1 || $2 })(lhs, rhs)
}

public func >= (lhs: NSDate, rhs: NSDate) -> Bool {
    return compareWithOperation({ $0 > $1 || lhs == rhs }, { $0 || $1 || $2 })(lhs, rhs)
}

public func < (lhs: NSDate, rhs: NSDate) -> Bool {
    return compareWithOperation({ $0 < $1 }, { $0 || $1 || $2 })(lhs, rhs)
}

public func <= (lhs: NSDate, rhs: NSDate) -> Bool {
    return compareWithOperation({ $0 < $1 || lhs == rhs }, { $0 || $1 || $2 })(lhs, rhs)
}

public func != (lhs: NSDate, rhs: NSDate) -> Bool {
    return !(lhs == rhs)
}

**Comment by elsesiy** [comment]
@zsw12abc I don't have any, can you please give me some information on how to reproduce it?

**Comment by zsw12abc** [comment]
i just installed it again this morning and it worked well.
i don't know what happened last time.
but now, everything is good

**Comment by elsesiy** [comment]
Alright, thus -> closed
