### ISSUE TITLE
Convert an NSDate, or string, or cvdate, to DayView? Possible?

### ISSUE THREAD

**Issue by joelwass** [Mozharovsky/CVCalendar#152]
Is it possible to convert NSDate, or a string of a date, or a CVDate to a DayView object?

can't figure out how, been trying to hack around for a while. 

Appreciate it, Mozharovsky

**Comment by elsesiy** [comment]
@joelwass So I looked into your issue but couldn't figure out what you're trying to do? Date is a property of the dayview object as you've probably seen, so there're lot of properties to be set in order to have a fully working dayview object (take a look at the public vars and the init). So?
