### ISSUE TITLE
Seems the Calendar isn't Working At All (iOS 9.1.2)

### ISSUE THREAD

**Issue by Archivus** [Mozharovsky/CVCalendar#154]
Hey,
So I've followed the storyboard set up, took a look at the Demo Project and followed everything on there, but it seems the calendar is no longer working on the aforementioned version? I've attached my code. I even took out all constraints from my views to see if sizing was an issue but to no avail. What am I doing wrong?
<img width="701" alt="screen shot 2015-11-04 at 9 40 38 am" src="https://cloud.githubusercontent.com/assets/1841186/10941159/233c0bb2-82d8-11e5-89cc-cbd385d4452a.png">

**Comment by joelwass** [comment]
are you implementing the extension of the calendar controller within this class? you can download the demo and see how the code is set up in that

**Comment by Archivus** [comment]
I literally just copy pasted the code into a clean Xcode project and built: the menu view appears as a white view while the calendar view does not appear at all. Same as before :(

**Comment by Archivus** [comment]
Fixed the issue. Fault was mine. Sorry for the bother!

**Comment by Incyc** [comment]
@Archivus would you mind mentioning here what the issue was? I seem to be having the exact problem. Thanks!

**Comment by Archivus** [comment]
@Incyc in Interface Builder go to 'Connections' in the Inspector and drag the view's 'delegate' and 'datasource' to the View Controller :)

**Comment by tommypacker** [comment]
Hey @Archivus, did you have an issue with the calendarView being misaligned from the menuView, cause that's what I'm getting
