### ISSUE TITLE
Calendar reload

### ISSUE THREAD

**Issue by anthonycastelli** [Mozharovsky/CVCalendar#156]
There should be a way to reload the calendar. I fetch data (calendar events) from a server and I want to add a dot for them on the calendar, but there isn't a way to trigger the calendar to reload after the data is received. Are there any plans to add such a method or is there a way I can force it to reload?

**Comment by joelwass** [comment]
see the pull request, as soon as they merge my pull request there will be a method to refresh the calendar view, i can also work on a more advanced refresh depending on what you need

**Comment by anthonycastelli** [comment]
Okay sweet! Basically all I need the reload for is to add dots for days that have actives.

**Comment by joelwass** [comment]
so the adding dots method in the demo has a parameter of dayView. so you can call the refreshMonth method that is new in my pull request and it will call the dots method in the demo for each dayView in the month... does that make sense?

**Comment by elsesiy** [comment]
done :)

**Comment by anthonycastelli** [comment]
I took a look at your PR. Basically I have this now: 
```
extension CVCalendarContentViewController {
    public func refreshPresentedMonth() {
        for weekV in presentedMonthView.weekViews {
            for dayView in weekV.dayViews {
                removeCircleLabel(dayView)
                dayView.preliminarySetup()
                dayView.supplementarySetup()
                dayView.dotMarkers.removeAll()
                dayView.reloadContent()
            }
        }
    }
}
``` 

When I reload the dayView, clicking days leaves the elected circle visible. Am I missing something?

**Comment by joelwass** [comment]
I'm not sure i understand your question

**Comment by anthonycastelli** [comment]
Here is my setup:

I'm communicating with a server to retrieve calendar events. I then parse the events and want to add a dot marker on the calendar. Since the data is received after the calendar is loaded I need to reload everything that way the delegate methods are called to setup the markers on the calendar for given days. My dilemma is that when I get everything to reload and the dots to appear, selecting days leaves the election marker visible like so

<img width="595" alt="screen shot 2015-11-09 at 12 43 23 pm" src="https://cloud.githubusercontent.com/assets/2137365/11045992/7e59810e-86df-11e5-80a7-7b79edb03a77.png">

**Comment by joelwass** [comment]
oh yea so the dot marker isn't refreshed in my pull request. only the
circle view. i can work on refreshing the dot view in the next few days.

**Comment by joelwass** [comment]
my refresh month calls my delete circle view method, which only deletes the
circle view not the dot view too. i'll work on the dot view

**Comment by anthonycastelli** [comment]
That would be great!

**Comment by joelwass** [comment]
the pull request https://github.com/Mozharovsky/CVCalendar/pull/160 fixes your issue, pressure them to merge and you'll be able to do what you're intending to do

**Comment by anthonycastelli** [comment]
Cool, thank you for your work! Will test it out tonight!

**Comment by neugartf** [comment]
Acutally, you are not reloading the dots in your "refreshPresentedMonth()" method, you'd need to call dayView.setupDotMarker() and dayView.topMarkerSetup() right after deleting them. Otherwise it's not a refresh at all.

**Comment by 16x9** [comment]
If I may reenforce neugartf’s comment, the newly added refreshPresentedMonth() method does a fine job of removing existing Dot Markers (thanks so much for this addition :) ) but there doesn’t appear to be any attempt being made to repopulate the calendar’s date cells with potentially revised Dot Markers.

**Comment by stefreak** [comment]
@16x9 i think that is now fixed in master ... since #180 :)

**Comment by elsesiy** [comment]
As stated correctly by @stefreak it is, hence closed!
