### ISSUE TITLE
Initialize Selected Date

### ISSUE THREAD

**Issue by trevor-winters** [Mozharovsky/CVCalendar#168]
Hello,

I am trying to select an initial date upon ViewDidLoad instead of today's date. Is there a way to do this?

Thanks!

**Comment by trevor-winters** [comment]
Figured it out. For those wondering:
override func viewDidLoad()
    {
        ...
        self.calendarView.toggleViewWithDate(NSDate())
    }

Replace NSDate() with your date.

**Comment by bjaskj** [comment]
Is there a way to prevent it from animating the change?
