### ISSUE TITLE
Warnings in Library

### ISSUE THREAD

**Issue by jose920405** [Mozharovsky/CVCalendar#169]
If it's not too much trouble could correct please all the warnings that are in the latest version of pods.

It is that my boss is a little picky about these things

![unnamed-1](https://cloud.githubusercontent.com/assets/12536184/11383142/30e966b8-92d4-11e5-8e8e-50ad71973f26.png)

![unnamed](https://cloud.githubusercontent.com/assets/12536184/11383143/335e15ec-92d4-11e5-9df8-2103f89136a3.png)

**Comment by elsesiy** [comment]
@jose920405 You're not using the latest version of the library. Please run pod update to get 1.2.7 where most of the warnings have been removed. Please verify in the future that there issue isn't on your side prior to open up a ticket, otherwise it's quite cumbersome for us...

**Comment by jose920405** [comment]
I'm sorry but I check this before opening this ticket.
My podfile.lock 
![unnamed](https://cloud.githubusercontent.com/assets/12536184/11398428/99e565fc-934e-11e5-9b00-c8aedaf07d5f.png)

My xcode sersion

![unnamed-1](https://cloud.githubusercontent.com/assets/12536184/11398432/a7546792-934e-11e5-99c4-89d52d1ed8d6.png)

Is it possible that something in the version of xcode?

**Comment by elsesiy** [comment]
I don't think so. Have you tried specifying the git repository directly and thus using the master branch instead of a released version? According to the release history, my commit was included but I need to create a sample project and see if there're still warnings...

**Comment by Nykho** [comment]
I think this is related to the project. The commit with the fixes:

https://github.com/Mozharovsky/CVCalendar/commit/619b23984640ba1c37d30b614e97518c14e84add

was on November 1 and the release of CVCalendar 1.2.7 was on Oct 16.

I think you need to do a new release so the new commits are included.

**Comment by jose920405** [comment]
I think that the problem is related with this.
https://github.com/Mozharovsky/CVCalendar/issues/170

**Comment by neugartf** [comment]
Since #170 is closed, I'm assuming that this has also been resolved for you. Give us a short notice here otherwise.
