### ISSUE TITLE
Animating between CVCalendarViewModes

### ISSUE THREAD

**Issue by yuriferretti** [Mozharovsky/CVCalendar#17]
I'd like to know if it's possible to animate between the CVCalendarViewModes. It would be great if so!

**Comment by Mozharovsky** [comment]
Hello @yuriferretti, 

Thank you for suggested feature. I'll cover its implementation this weekend. 

Regards, 
Euegene

**Comment by yuriferretti** [comment]
@Mozharovsky glad to hear that! Your cAlencar is awesome!

**Comment by youpiii** [comment]
Really like it!

**Comment by youpiii** [comment]
hello,
Can you plz show the way to access the calendarMode variable from my view, so maybe with a button click i can animate between the CVCalendarViewModes.

Thanks,
Awesome App (Y)

**Comment by martjemeyer** [comment]
I'm not sure if this is because the WeekView mode is not fully operational yet, or do I need to change more settings then just changing the WeekView mode? I run this from a new view, same setup as the MonthView.
Since I don't want the WeekView to be 200 pixels high to fit nicely :)

![screenshot 2015-04-21 13 22 13](https://cloud.githubusercontent.com/assets/9798987/7251296/69f5df18-e82a-11e4-8146-6bd04a812ba2.png)
![screenshot 2015-04-21 13 28 19](https://cloud.githubusercontent.com/assets/9798987/7251298/6eab8bde-e82a-11e4-8155-beca4db5a42a.png)

**Comment by Mozharovsky** [comment]
Hello @martjemeyer, 

The current mathematical model for rendering is totally wrong since it's creating different sizes for every month view and its subviews regarding to the container's size. It's going to b reworked this weekend. So more changes to come!

Regards, 
Eugene

**Comment by martjemeyer** [comment]
Ok! With some dragging and cheating it has the looks I want it for now, so I can update it later when the code is updated :)
Thanks again for you hard work!

**Comment by Mozharovsky** [comment]
Hello @martjemeyer, 

The latest [changes](https://github.com/Mozharovsky/CVCalendar/tree/develop) fix your issue. Now CVCalendar properly constructs week and day views depending on the mode. Plus in MonthView mode CVCalendar dynamically updates the container to it perfectly fits its content. It's adapted to AutoLayout. 

Please, let me know if it works for you. 

Regards, 
Eugene

**Comment by Mozharovsky** [comment]
Hello @yuriferretti, 

From now CVCalendar supports animated transition between modes. Simply use CVCalendarView Convenient API in your controller. The code sample is below. 

```swift 
    /// Switch to WeekView mode.
    @IBAction func toWeekView(sender: AnyObject) {
        calendarView.changeMode(.WeekView)
    }
    
    /// Switch to MonthView mode.
    @IBAction func toMonthView(sender: AnyObject) {
        calendarView.changeMode(.MonthView)
    }
```

In case of any issues or bugs please let me know. 

Regards, 
Eugene

**Comment by martjemeyer** [comment]
Great work! I'll check it out soon!

**Comment by Mozharovsky** [comment]
This is how it looks with 40 points container in height. 

![screen shot 2015-04-26 at 17 02 53](https://cloud.githubusercontent.com/assets/6762769/7339245/36412ce4-ec36-11e4-8fc3-c681ce221091.png)

**Comment by yuriferretti-luizalabs** [comment]
Awesome!! I'll check it out as soon as possible
