### ISSUE TITLE
Pod version 1.2.7 is not updated

### ISSUE THREAD

**Issue by msawvov** [Mozharovsky/CVCalendar#170]
The current code in library (pod version)
![screen shot 2015-11-25 at 11 44 01 am](https://cloud.githubusercontent.com/assets/16020011/11403333/40d82398-936a-11e5-947d-baebedc7e06d.png)

The current code in library (CVCalendar Demo)
![screen shot 2015-11-25 at 11 49 19 am](https://cloud.githubusercontent.com/assets/16020011/11403403/9bdcdf22-936a-11e5-823c-57279c403cd0.png)

**Comment by FranzBusch** [comment]
+1

**Comment by jose920405** [comment]
This issue will be taken into consideration?

**Comment by jose920405** [comment]
actually they are so difficult to do this?

**Comment by jose920405** [comment]
really is so hard to do this?

**Comment by elsesiy** [comment]
@jose920405 No it's not, I prepared everything, just waiting for @Mozharovsky to add me as collaborator for contributing to the pod trunk as well...

**Comment by Paulo-Branco** [comment]
It's been 23 days since this issue was opened. It was referenced by multiple persons. What's preventing you from fixing this / updating the pod trunk ?

**Comment by elsesiy** [comment]
Done

**Comment by jose920405** [comment]
Thanks man
