### ISSUE TITLE
Reloading calendar?

### ISSUE THREAD

**Issue by seenickcode** [Mozharovsky/CVCalendar#175]
Hello, is there a way to re-trigger ``func supplementaryView(shouldDisplayOnDayView dayView: DayView) -> Bool`` after the calendar view is loaded?  Thanks

**Comment by stefreak** [comment]
already fixed in master ... should be closed

`calendarView.contentController.refreshPresentedMonth() `

**Comment by seenickcode** [comment]
Ok Thank you!

**Comment by seenickcode** [comment]
@stefreak for now I manually copied and pasted the code in to my codebase.  Will I have to wait until the podspec is updated for it to be officially available?

**Comment by stefreak** [comment]
For it to be officially available yes, but you can also just do this until a new version is released: https://guides.cocoapods.org/using/the-podfile.html#from-a-podspec-in-the-root-of-a-library-repo

**Comment by seenickcode** [comment]
Great thanks

On Thu, Dec 10, 2015 at 11:42 AM, Steffen Neubauer <notifications@github.com
