### ISSUE TITLE
reload dots

### ISSUE THREAD

**Issue by javierdac** [Mozharovsky/CVCalendar#177]
I am using the next functions:

func dotMarker(colorOnDayView dayView: CVCalendarDayView) -> [UIColor] 
func dotMarker(shouldMoveOnHighlightingOnDayView dayView: CVCalendarDayView) -> Bool
func dotMarker(shouldShowOnDayView dayView: CVCalendarDayView) -> Bool

those functions are calling when the calendar show up. is it possible to calling it again like a restart or refresh?

Best!

**Comment by sallyahmed** [comment]
yes u can by adding dayView.setupDotMarker() in method 


 public func refreshPresentedMonth() {
        for weekV in presentedMonthView.weekViews {
            for dayView in weekV.dayViews {
                removeCircleLabel(dayView)
                removeDotViews(dayView)
                dayView.preliminarySetup()
                dayView.supplementarySetup()
                dayView.setupDotMarker()
            }
        }
    }

**Comment by elsesiy** [comment]
Please see the referenced PR for further reference.
