### ISSUE TITLE
How add dates to be marked on the Calendar?

### ISSUE THREAD

**Issue by thetof91** [Mozharovsky/CVCalendar#179]
Hello

I'm trying to use this calendar. But I'm a bit confused over how do I mark some days to show there is something planned for that date? I got a array with my NSDates..

**Comment by keval9999** [comment]
you can easily set your own array date 
its working 
put folloing code in  (func dotMarker(shouldShowOnDayView dayView: CVCalendarDayView) -> Bool)

function : - 
 func dotMarker(shouldShowOnDayView dayView: CVCalendarDayView) -> Bool {

        let dateformatter = NSDateFormatter()
        dateformatter.dateFormat = "yyyy/MM/dd"
        let date2 = dateformatter.stringFromDate(dayView.date.convertedDate()!)
        for(var i=0;i<date_Array.count;i++)
        {
            if(date2==date_Array[i])
            {
                return true
            }
        }
        return false

    }


date_array is my date array

**Comment by thetof91** [comment]
Thanks :)

Will try that.

**Comment by keval9999** [comment]
:+1:

**Comment by neugartf** [comment]
Seems to be solved
