### ISSUE TITLE
Calling didSelectDayView immediately on load

### ISSUE THREAD

**Issue by csima** [Mozharovsky/CVCalendar#18]
Why does this happen? It's now difficult to tell if a user selects the actual date vs it happening on view.

**Comment by Mozharovsky** [comment]
Hello @csima, 

When a CVCalendar is being created it's also creating its MonthViews. Each MonthView, in its turn, is creating a set of WeekViews and they're doing ultimately the same with DayViews. So this is the point you're asking about. Once a DayView that represents the current day is created its Container (MonthView) receives a selection event and passes it to the appropriate delegate. 

In a few words, it's a little bug inside of CVCalendar. I'll fix it on the coming maintenance. 

Thank you for reporting!

Regards, 
Eugene

**Comment by csima** [comment]
Do you have any kind of workaround I might be able to apply or do myself in the meantime?

**Comment by Mozharovsky** [comment]
Fixed in the [pre-release version](https://github.com/Mozharovsky/CVCalendar/releases/tag/1.1.0).

**Comment by dgdosen** [comment]
On this one - I like the idea of only "selecting a day view" if the user touches a day, not if the user changes a month view, and the first day of the month is selected for you...

It's be great to distinguish between a true date selected, and a date defaulted (like the 1st on a swipe)..

My reason for asking is that if a user selects a date, I want to unwind a view on that selected date.  Kind of like selecting OK/Back at the same time.
