### ISSUE TITLE
Getting Error When Declaring CalandarView

### ISSUE THREAD

**Issue by kamalupasena** [Mozharovsky/CVCalendar#182]
i am getting following error when  i am trying to map storyboard view to ViewContoller 
'weak' cannot be applied to non-class type '<<error type>>'

**Comment by Archivus** [comment]
Would you mind expounding on what it is you're trying to do exactly?

**Comment by kamalupasena** [comment]
this is what i have done i have added two views on my storyboard i have to add those two views to my viewcontroller  like this ` @IBOutlet weak var calendarView: CVCalendarView!` but after i do that i am getting above error  'weak' cannot be applied to non-class type '<>'

**Comment by leojkwan** [comment]
Getting the same issue!

**Comment by yjradeh** [comment]
same

**Comment by vishnupradeep93** [comment]
Same here.

**Comment by neugartf** [comment]
Can't reproduce. 
Did you set the custom class on the CVCalendarView?
What are your steps exactly?

**Comment by vishnupradeep93** [comment]
It was actually some error with cocoa pods or Xcode. If the module was not set on storyboard to CVCalendar this issue occurs. Also, I didn't import the framework on view controller class... Solved it anyway...

**Comment by neugartf** [comment]
Thank you for your fast response. I hope that's gonna help the others as well. 
*Closed*

**Comment by leojkwan** [comment]
Thanks everyone as well.
