### ISSUE TITLE
CVCalendar for Objective-C

### ISSUE THREAD

**Issue by nitin-agam** [Mozharovsky/CVCalendar#183]
Is this library available for Objective-C also?

**Comment by elsesiy** [comment]
Unfortunately not, this is a pure Swift-based library. But as stated by Apple (I haven't tried it myself yet) there's a way to use Swift also in your Obj-C codebase. Please see https://developer.apple.com/library/ios/documentation/Swift/Conceptual/BuildingCocoaApps/MixandMatch.html
for further reference..

**Comment by Rodolfocartas** [comment]
It works as documented on Apple's documentation. I've had no problems including the control in my app.

**Comment by elsesiy** [comment]
@Rodolfocartas Thanks for pointing that out. @nitin-agam I'm gonna close the issue for now, if there're further remarks please feel free to comment!

**Comment by nitin-agam** [comment]
Thanks! @Rodolfocartas
