### ISSUE TITLE
Ability to show only 2 weeks?

### ISSUE THREAD

**Issue by seenickcode** [Mozharovsky/CVCalendar#19]
Hello, I read the docs as best I could but didn't find the ability to just show the last, say, two weeks instead of the entire month. 

Thanks,

**Comment by Mozharovsky** [comment]
Hello @seenickcode, 

We were discussing of how to show only a week in order to save some space in #13 issue. Take a look, I've put the description of using. 

Though I haven't updated docs yet since more updated are coming. 

If you have any questions ask me here. Hope it helps!

Regards, 
Eugene

**Comment by seenickcode** [comment]
+1 thanks
