### ISSUE TITLE
AppearanceDelegate

### ISSUE THREAD

**Issue by Mr-Getting-It-Done** [Mozharovsky/CVCalendar#203]
Hey

I think you have changed the 
```Swift
calendarView.appearanceDelegate
```
 to something else and forgot to update your readme file?
Since Xcode complaints after I copy the code in the readme to set the delegates.

BTW, it is a very nice calendar :)

**Comment by elsesiy** [comment]
@Mr-Getting-It-Done As far as I can tell there hasn't been any changes to the mentioned line. Could you name the file and also what the actual issue is? Thanks!

**Comment by jtjacka** [comment]
@elsesiy  It looks like it may now be calendarView.calendarAppearanceDelegate

**Comment by neugartf** [comment]
Has been fixed in 2bb7176 accordingly. Thanks :+1:
