### ISSUE TITLE
Carthage

### ISSUE THREAD

**Issue by JBMyapphone** [Mozharovsky/CVCalendar#204]
Hi,
Please, Could you make you project compatible with Carthage(https://github.com/Carthage/Carthage) ?
Thank you.

**Comment by elsesiy** [comment]
@JBMyapphone We'll have a look at it soon

**Comment by JBMyapphone** [comment]
Thank you.
You just have to create a shared scheme which contains project classes.
At least, it's work in my case.

**Comment by sprint84** [comment]
Hi, I loved the project too and would love to have it Carthage compatible. I'll try to fork it and send a pull request

**Comment by sprint84** [comment]
Here it is:
https://github.com/Mozharovsky/CVCalendar/pull/214

**Comment by elsesiy** [comment]
@sprint84 Thanks for your submission! I'll take a look at it within the next couple days.

**Comment by hoangtuanfithou** [comment]
Dear all
@sprint84 @JBMyapphone 
Is the project now compatible with Carthage ?

**Comment by sprint84** [comment]
@hoangtuanfithou yes, it is!

**Comment by hoangtuanfithou** [comment]
@sprint84 Thanks :v: 
And have a nice day (It is in the morning in myside)
Thanks

**Comment by hoangtuanfithou** [comment]
@sprint84 :
Project target can not set to 8.0

![screen shot 2016-03-01 at 6 00 24 pm](https://cloud.githubusercontent.com/assets/93890/13425184/c50bd470-dfd7-11e5-85a2-75ed342781d7.jpg)
