### ISSUE TITLE
Menuview graphical bug after commitMenuViewUpdate()

### ISSUE THREAD

**Issue by peter9teufel** [Mozharovsky/CVCalendar#205]
I have a graphical bug after calling commitMenuViewUpdate() on the menuview, after calling it the menuview shows the original layout it has before the call to the method and overlays the fixed layout after the call.

I'm using auto layout.

Here's a screenshot how it looks like.
![bildschirmfoto 2016-01-14 um 08 43 01](https://cloud.githubusercontent.com/assets/1713402/12318490/05459cf4-ba9b-11e5-9265-5957bacd6b4e.png)

Any suggestions?

THX and best regards,
Peter

**Comment by sreeji44** [comment]
how you change that lines in each date ?

**Comment by elsesiy** [comment]
@peter9teufel Please verify that the delegate wasn't set twice..I encountered the same issue after having it set via Storyboard and in a property observer.
Other than that, please let me know what you've tried so far and how your current setup looks like, otherwise I can't help you out...

**Comment by peter9teufel** [comment]
That's it! Thx a lot for your support and your great calendar module!
