### ISSUE TITLE
Changing default background colours for current day and selected day

### ISSUE THREAD

**Issue by r3mus** [Mozharovsky/CVCalendar#211]
Been looking around in the docs and wiki but can't find anything about how (or if it's even possible) to change default background colours? If so, can you please point me in the right direction?

Thanks!

**Comment by keval9999** [comment]
Dear 3mus
You can change default background color for current day & selected day using CVCalendarViewAppearance.swift file 
set color to  dayLabelPresentWeekdaySelectedBackgroundColor variable for current day & for selected day set color in dayLabelWeekdaySelectedBackgroundColor variable 
you can  manage font size,color,alpha  too.

Thanks!

**Comment by elsesiy** [comment]
@r3mus As @keval9999 stated correctly use the public properties of CVCalendarViewAppearance to adjust the calendar appearance to suit your needs. --> closed

**Comment by r3mus** [comment]
Ah! Thanks guys. Wasn't actually sure what 'dayLabel' referred to. Appreciate the quick response!

**Comment by mohitkumar001** [comment]
i want to change the dayLabel text color for some dates(passed in an array) while i have got the correct output in first month but when i go to next month and check with another values(new array values) the current month data is mess up with previous one. anyone can help? big thanks in advance
