### ISSUE TITLE
CVCalendarView is blank

### ISSUE THREAD

**Issue by Torbold** [Mozharovsky/CVCalendar#216]
Hi there!

I have ran into an issue. I have everything setup as it should be:
 - the views in Storyboard have their classes set to CVCalendarView and CVCalendarMenuView
 - IBOutlets are connected
 - Delegates for Menu and Calendar are added to the class and required methods are implemented
 - view updates are commited in :viewDidLayoutSubviews:
 - I have made sure that the views are actually here (checked autoLayout constraints)

But the views are empty (names of weekdays are present, but not the calendar itself). Tried to reinstall the pod - didn't work out for me.
Are there any hints towards what I am doing wrong?

Below is the code (or as a screenshot - http://prntscr.com/9sy8yz) and a screenshot of Storyboard setup (http://prntscr.com/9syaz6):

    import UIKit
    import CVCalendar

    class DatePickerCVC: UIViewController {

        @IBOutlet weak var calendarView: CVCalendarView!
        @IBOutlet weak var menuView: CVCalendarMenuView!
        @IBOutlet weak var bottomPanelView: UIView!
    
        var searchParams: AviasalesSearchParams!
    
        override func viewDidLoad() {
            super.viewDidLoad()
        }

        override func viewDidLayoutSubviews() {
            menuView.commitMenuViewUpdate()
            calendarView.commitCalendarViewUpdate()
        }
    
        override func didReceiveMemoryWarning() {
            super.didReceiveMemoryWarning()
            // Dispose of any resources that can be recreated.
        }

    }
    
    extension DatePickerCVC: CVCalendarViewDelegate, CVCalendarMenuViewDelegate {
    
        // Required method to implement!
        func presentationMode() -> CalendarMode {
            return CalendarMode.MonthView
        }
    
        /// Required method to implement!
        func firstWeekday() -> Weekday {
            return Weekday.Monday
        }
    }

Thanks in advance,
Mikhail

**Comment by Torbold** [comment]
Playing with AutoLayout constraints fixed it. Sorry for bothering, guys.

**Comment by elsesiy** [comment]
@Torbold Great, hence closed!
