### ISSUE TITLE
Project warning, unused capture dayview

### ISSUE THREAD

**Issue by simonmcl** [Mozharovsky/CVCalendar#218]
Code has introduced a warning to my project. Inside CVCalendarViewAnimator, line 35, there is an unused capture "dayView"

```swift
public func animateSelectionOnDayView(dayView: DayView) {
        let selectionAnimation = delegate.selectionAnimation()
        dayView.setSelectedWithType(.Single)
        selectionAnimation(dayView) { [unowned dayView] _ in
            // Something...
        }
    }
```

**Comment by elsesiy** [comment]
@simonmcl Yes we noticed that as well. Might clean the warning sometime soon :)

**Comment by drieran** [comment]
Please clean up this warning. It's easy:
let _ = dayView

**Comment by danielvivek2006** [comment]
let _ = dayView throws an error saying **"attempted to retain deallocated object"** in swift 3.0 and 
'CVCalendar', '1.4.1'
![screen shot 2017-03-27 at 15 40 18](https://cloud.githubusercontent.com/assets/10789472/24351544/bc14d5a0-1303-11e7-8d5f-5a2a23e11dd6.png)
