### ISSUE TITLE
Add different color of event

### ISSUE THREAD

**Issue by Xc0d3dev** [Mozharovsky/CVCalendar#224]
You can add a different color to each event I want each type of event has a different color as you have to add. Image preview 
Thanks
[http://postimg.org/image/6maiq138h/](url)

**Comment by elsesiy** [comment]
You can add different colors for different events easily buy implementing `optional func dotMarker(colorOnDayView dayView: DayView) -> [UIColor]` of the `CVCalendarViewDelegate`. If you've further questions, do not hesitate to ask :)
