### ISSUE TITLE
Is there a way to draw separator lines between the dates? 

### ISSUE THREAD

**Issue by spandana-batchu** [Mozharovsky/CVCalendar#226]
The easiest way to do this was to set a border to the DayView in the delegate call back, but since few days have adjacent days and few dont, the thickness of the line is not consistent through out as you can see in the below picture. 
Is there a way I can draw a path between the DayViews instead ? 
<img width="404" alt="dayviews with border" src="https://cloud.githubusercontent.com/assets/13753715/12972695/5f4bd838-d0cd-11e5-8630-6b69de14e7a9.png">

**Comment by neugartf** [comment]
What might work is to set self.calendarView!.changeDaysOutShowingState(false), didn't try it by myself though. There would be still a thinner line on top and bottom of course.

Is the issue to provide a grid option for the whole calendar or to provide a custom UIView to each DayView (even though they are not shown)? Maybe we can provide one of those options in 2.0.0

**Comment by neugartf** [comment]
I just found an issue where @kooliokey implemented that feature, I think. (#198) Maybe he can provide some information.

**Comment by spandana-batchu** [comment]
Thanks @neugartf ! I needed it only to provide a grid option.  So, I drew only top and left borders to the DayView for each cell and inserted a right and bottom border to the outer calendar view which solved my problem. However I had to  shouldShowWeekdaysOut to false in order for that solution to work.

**Comment by neugartf** [comment]
Great :) I'm gonna close this issue then.
