### ISSUE TITLE
add date on supplementaryView

### ISSUE THREAD

**Issue by Xc0d3dev** [Mozharovsky/CVCalendar#228]
Hi, what is step to add new date on supplementaryView.

```
func supplementaryView(shouldDisplayOnDayView dayView: DayView) -> Bool {
        if (Int(arc4random_uniform(5)) == 1) {
            
            return true

        }
        return false
    }

```

**Comment by elsesiy** [comment]
@Xc0d3dev Sorry, I don't understand what the question is here...Could you please specify what you need to know to have this issue closed? Thanks!

**Comment by Xc0d3dev** [comment]
add new event on calendar.

**Comment by Xc0d3dev** [comment]
Has been solved. Code Here. Date array is add date 

    func supplementaryView(shouldDisplayOnDayView dayView: DayView) -> Bool {
        let dateformatter = NSDateFormatter()
        dateformatter.dateFormat = "yyyy/MM/dd"
        let date2 = dateformatter.stringFromDate(dayView.date.convertedDate()!)
        let date_Array = ["2016/02/10","2016/02/11","2016/02/12"]
        for(var i=0;i<date_Array.count;i++)
        {
            if(date2==date_Array[i])
            {
                return true
            }
        }
        return false
    }
}
