### ISSUE TITLE
CVDate with month = 0 and month = 13

### ISSUE THREAD

**Issue by guidolodetti** [Mozharovsky/CVCalendar#23]
Little bug in CVCalendarDayView on line 81, where it increments months up to number 13 and 0. My fix for it:
```    
var year = calendarManager.dateRange(self.weekView!.monthView!.date!).year
var month: Int? = calendarManager.dateRange(self.weekView!.monthView!.date!).month
if self.isOut {
    if day > 20 {
        if (month! == 1){
                month! = 12;
                year -= 1;
        } else {
                month! -= 1
         }
    } else {
        if (month! == 12){
            month! = 1;
            year += 1;
        } else {
            month! += 1
        }
    }         
    if !shouldShowDaysOut {
       self.hidden = true
    }
}`
```

**Comment by Mozharovsky** [comment]
Hello @vuk0dl4k, 

I don't understand where you found a bug. This snippet of code is responsible for figuring out the day's out initial month. Basically there are certain days out (which don't belong to the presented month), so in this code sample we figure out if a particular day view belongs to either previous or next month. 

It doesn't seem to be working wrong. If it does let me know the way it fails working correctly. 

Regards, 
Eugene

**Comment by vuk0dl4k** [comment]
Hello Eugene,
the UI is loaded properly, but if you check the CVDate property for those calendar cells, the attributes are wrong (month = 13, month = 0...). This happens when CVCalendarView is configured to show days out.

I hope you understand me,
Guido

**Comment by Mozharovsky** [comment]
Hello @guidolodetti, 

Thank you for reporting this issue. It turns out that the process of initialising CVDate properties is wrong for days out. I'll apply your fix in the coming release. 

Regards, 
Eugene
