### ISSUE TITLE
How do i reload the calendar view?

### ISSUE THREAD

**Issue by patchthecode** [Mozharovsky/CVCalendar#234]
I need to have the delegate called again (the delegate function to know if a dateView should have an accessoryView or not). How to I make the calendarView reload it self?

**Comment by elsesiy** [comment]
@patchthecode Is this still an issue? Are you trying to update a single month or the whole calendar? Please have a look at #267

**Comment by patchthecode** [comment]
ok thanks. its no loner an issue
