### ISSUE TITLE
Changelog has not been updated in 9 months

### ISSUE THREAD

**Issue by johnjiang** [Mozharovsky/CVCalendar#235]
Can we please start updating the changelog again? It's difficult to know what bug fixes have been made and/or features added.

**Comment by elsesiy** [comment]
@johnjiang You're absolutely right, you can see what has changed by scrolling through the release-tags but we'll also update the changelog.md soon :yum:

**Comment by elsesiy** [comment]
Done with https://github.com/Mozharovsky/CVCalendar/commit/8a10b090a247008a48cc878166fc6274bb5272fc
