### ISSUE TITLE
unable to get the right NSDate back

### ISSUE THREAD

**Issue by slowtree** [Mozharovsky/CVCalendar#236]
Hi guys,
I'm probably missing something here, I'd like to get the current NSDate selected and I can't get it to work.
Whenever I try to use the convertedDate()  method it returns me the date as the day before at 23 (11PM).  Could you please help me out, I'm sure what's going wrong.

Thanks in advance!

**Comment by slowtree** [comment]
It was just the debugger output that was wrong. Don't know what to say, when you try to format it, you get the right value.

**Comment by neugartf** [comment]
Yeah, thats just a timezone issue (:

**Comment by abhinavnair** [comment]
@neugartf I am also facing the same issue. Could you please suggest me how to convert it to a particular timezone? I tried using NSDateFormatter and converting, but it doesn't work.

**Comment by neugartf** [comment]
The thing about NSDate is that it doesn't contain any time zone information.
Have you really tried setting the time zone in the NSDateFormatter object? https://developer.apple.com/library/mac/documentation/Cocoa/Reference/Foundation/Classes/NSTimeZone_Class/index.html#//apple_ref/swift/cl/c:objc(cs)NSTimeZone

**Comment by slowtree** [comment]
Sorry for the delay, @neugartf is right, the way I found that everything was working properly was to use and NSDateFormatter. Basically the debugger console was where I was getting the "wrong" date, but whenever I used the NSDate with a formatter, it worked fine.
