### ISSUE TITLE
Change colour of menu labels

### ISSUE THREAD

**Issue by SimonTheEngineer** [Mozharovsky/CVCalendar#242]
I'm trying to figure out how to change the weekday label text colour for the menuView.

Any ideas? 

Thanks!

**Comment by keval9999** [comment]
> In `CVCalendarMenuView.swift` file set color of `dayOfWeekTextColor` variable.

**Comment by SimonTheEngineer** [comment]
Excellent, haven't tried it yet but I'm sure it'll work :+1: thanks very much!
