### ISSUE TITLE
Installation problem

### ISSUE THREAD

**Issue by kgbisa** [Mozharovsky/CVCalendar#245]
I am receiving the "Command failed due to signal: segmentation fault: 11" error when running the CVCalendar. I am using Xcode 7.3 beta and Swift 2.

I tried three different methods and all gave me the same error:

1. I downloaded the libraries through Cocoapods and added it to an empty Xcode project.
2. I downloaded the zip file from the master view from the above Github, and ran the Demo Xcode project.
3. I downloaded the zip file from the "developer" view from the above Github, and ran the Demo Xcode project.

All three methods above gave me the segmentation fault 11 error.

To make sure that this is not a Ruby or Cocoapod problem, I downloaded the Ice cream Xcode project and Alamofire Cocoapod (from this website: https://www.raywenderlich.com/97014/use-cocoapods-with-swift) and confirmed that this error does not occur.

Any help would be greatly appreciated, thanks in advance!!

**Comment by awedeebawe** [comment]
If you are using XCode 7.3 beta the problem is with the ++ increment operator. This is deprecated in the new swift language update. Downgrade your XCode version.

**Comment by neugartf** [comment]
Is this still an issue @kgbisa?

**Comment by kgbisa** [comment]
Thank you for your help!
