### ISSUE TITLE
range selection

### ISSUE THREAD

**Issue by nasser-halabi** [Mozharovsky/CVCalendar#248]
Thank you for the beautiful library.
I'm trying to use the range selection functionality and it seems that it's not yet completely built. I'm a little confused, how can I access the current MonthView so I can loop through the days in the range and highlight them?
Maybe I missed them but if you have any diagrams of the project showing the logical flow of the functions I would really appreciate having a look at them, that would make our lives much easier.

Thanks

**Comment by elsesiy** [comment]
@nasser-halabi As discussed in #222 range selection is currently not part of the project. It'll be added in a future version as already requested in #12

**Comment by RIju912** [comment]
By when we can expect this one?
