### ISSUE TITLE
Set custom date

### ISSUE THREAD

**Issue by monsterfi** [Mozharovsky/CVCalendar#251]
Please I'd like to know if is now possibile to set a custom month/date in initialization phase of CVCalendar.
Thank you

**Comment by emjoseph** [comment]
Yeah I second that. It's important for when a user has already selected a date but is returning back to the calendar view to change it

**Comment by emjoseph** [comment]
Actually I believe I found the way to do it:
`self.calendarView.toggleViewWithDate(date)`

**Comment by monsterfi** [comment]
I tried in that way too but I supposed that was the same as a click on a custom date.
Am I making a mistake?
My issue is a little bit different: suppose you'd like to set your initial view (before any click) on a chosen month. Now it's march and I want a calendar view directly on July on app launching, how could we have it?

**Comment by emjoseph** [comment]
I haven't tried the situation you're describing personally, but I think the line above should work in your case if its called in the "viewDidLoad" or "viewWillAppear" methods of the view controller you want to launch the app with. 

In my case I call the function with the date I want to set the calendar too in the viewWillAppear method and it opens the calendar directly on the date I specified

**Comment by pavelhiq** [comment]
Hmm sounds strange - Im trying to call toggleViewWithDate(date) in viewDidLoad() but the calendar view  does not react on it! Selection remains empty unless you tap on some date...

**Comment by zuaaef** [comment]
Found a solution?

**Comment by pavelhiq** [comment]
not really.. seems it does not work at all unless shouldAutoSelectDayOnMonthChange is set to _true_,
so a number of strange assumptions about user interaction still holds in this library

**Comment by seenickcode** [comment]
Any updates to this?

**Comment by rlaferla** [comment]
+1

**Comment by elsesiy** [comment]
Should be fixed in #387
