### ISSUE TITLE
memory leakage.

### ISSUE THREAD

**Issue by hassiumsoft** [Mozharovsky/CVCalendar#252]
内存泄露

![Alt text](http://www.igiven.com/wp-content/uploads/2016/03/Main_storyboard_—_Edited.png)

![Alt text](http://www.igiven.com/wp-content/uploads/2016/03/Instruments.png)

**Comment by hassiumsoft** [comment]
in  CVCalendarContentViewController

```    
public let calendarView: CalendarView
```
to
```
public unowned let calendarView: CalendarView
```

**Comment by elsesiy** [comment]
Please see https://github.com/Mozharovsky/CVCalendar/commit/e3529b3b113ed4bfdd5d7b46f4043d10ce8c1537
Thank you!
