### ISSUE TITLE
Is their any way to view default look  as weekview.. Not the monthview

### ISSUE THREAD

**Issue by sreeji44** [Mozharovsky/CVCalendar#256]
i just want to view the calendar in weekview... when we open the calendar default look is weekview is their any way.. Thanks in advance

**Comment by sreeji44** [comment]
plz reply to this question... how can i make this calendar as weekview as default look

**Comment by elsesiy** [comment]
@sreeji44 CVCalendarView has a func to do exactly that (L288). Just take a look at the `public func changeMode(mode: CalendarMode, completion: () -> () = {})`. If you need further help, please let me know!

**Comment by sreeji44** [comment]
thanks but i look that and i changed this... by using this whether we want to edit the size of calendar view ??....

**Comment by sreeji44** [comment]
when i add this the design looks weird//.

**Comment by sreeji44** [comment]
hey what want to change in the change mode... ?

**Comment by sreeji44** [comment]
plz tell is very urgent

**Comment by sreeji44** [comment]
@elsesiy  Why you are not responding..... :(

**Comment by danielbmarques** [comment]
Did you call `changeMode(.WeekView)` at `viewDidLoad()` or `viewWillAppear()`? What happens then?

**Comment by sreeji44** [comment]
@danielbmarques 
![screen shot 2016-04-05 at 12 36 47 pm](https://cloud.githubusercontent.com/assets/16497980/14273728/54fc95f2-fb2a-11e5-97ed-27c32a725722.png)
ya when i add this....  i got an error


fatal error: unexpectedly found nil while unwrapping an Optional value

**Comment by sreeji44** [comment]
@danielbmarques  thankz i write that code on viewwillapper and work like charm thankzzz
