### ISSUE TITLE
New Install can not find CVCalendarView

### ISSUE THREAD

**Issue by justdan0227** [Mozharovsky/CVCalendar#257]
New user; long time ios developer.  Just tried this on new XCode 7.3. Installed via pod with:

source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '9.0'
use_frameworks!

pod 'CVCalendar', '~> 1.2.9'

and then added the following to my viewDidLoad

let myCalendar = **CVCalendarView**(frame: CGRectMake(0, 20, 300, 450))
and XCode is telling me unresolved identifier ?

**Comment by rmickeyd** [comment]
Did you import CVCalendar at top of file?

**Comment by justdan0227** [comment]
Nope... thanks! :)

**Comment by elsesiy** [comment]
@rmickeyd Thanks for helping out! Thus closed.
