### ISSUE TITLE
CVCalendarView disappears

### ISSUE THREAD

**Issue by khetag** [Mozharovsky/CVCalendar#258]
Xcode 7.2, Swift 2.0. I added two UIViews (with custom classes CVCalendarView and CVCalendarMenuView) as well as required delegates to UIViewController in Storyboard. Here is my code inside the VC: 
```swift
import UIKit
import CVCalendar

class ViewController: UIViewController, CVCalendarMenuViewDelegate, CVCalendarViewDelegate {

    @IBOutlet weak var menuView: CVCalendarMenuView!
    @IBOutlet weak var calendarView: CVCalendarView!
    
    
    override func viewDidLoad() {
        super.viewDidLoad()
        
    }
    
    override func viewDidLayoutSubviews() {
        super.viewDidLayoutSubviews()
        
        calendarView.commitCalendarViewUpdate()
        menuView.commitMenuViewUpdate() 
    }

    override func didReceiveMemoryWarning() {
        super.didReceiveMemoryWarning()
        // Dispose of any resources that can be recreated.
    }
    
    func presentationMode() -> CalendarMode {
        return CalendarMode.MonthView
    }
    
    func firstWeekday() -> Weekday {
        return Weekday.Monday
    }
}
```
Problem is that Calendar View disappears. I don't see the view anymore when I run the project. Menu View works fine. It doesn't look like it is an Auto Layout problem. What can cause the issue?

**Comment by khetag** [comment]
Found the reason. The following condition in ```CVCalendarView.commitCalendarViewUpdate()``` is evaluated to _false_:
```swift
let allowed = selfSize.width <= screenSize.width && selfSize.height <= screenSize.height
```
when the constraints for CVCalendarView from left/right are less than zero: 

![negative constraints](https://cloud.githubusercontent.com/assets/2349680/14003843/ee769fae-f155-11e5-82d4-9f3deb2598a1.png)

I fixed the constrains and the calendar appears now.

**Comment by MuhammadRizwan95** [comment]
how you did this can explain bit more plz?? im stuck on this issue.
