### ISSUE TITLE
i want to add some event for dates ? 

### ISSUE THREAD

**Issue by muhammet24** [Mozharovsky/CVCalendar#26]
Hi i checked your sample app. i saw some dot under the numbers,
How can i change the date with dot  and 
is there any way to put some information when they touch the numbers (pop-up menu) i want to add some event  and when the user touch it they will see the detail ?

**Comment by Mozharovsky** [comment]
Hello @muhammet24, 

CVCalendar is fully customisable. All you have to do is to figure out what you want and find the appropriate delegate to override its method(s). Check out delegates' description right [here](https://github.com/Mozharovsky/CVCalendar/wiki). As for events handling there is also an information about it so check wiki pages out. 

I will write an article of how to use all features of CVCalendar this week. Maybe I'll also record a video. I will inform you via email and out all links to this page. 

Regards, 
Eugene

**Comment by muhammet24** [comment]
thank you so much, you are so kind
