### ISSUE TITLE
Vertical month scrolling  

### ISSUE THREAD

**Issue by gmansata6290** [Mozharovsky/CVCalendar#260]
Is it possible for month scrolling in vertical instead of horizontal?

**Comment by elsesiy** [comment]
@gmansata6290 We're adding this feature in 2.0.0 :) If you've further remarks, feel free to reopen.

**Comment by cc-lam** [comment]
@elsesiy Hi, great library ! 

Do you have any ETA for 2.0 ? I'm really hoping to be able to use the vertical scrolling feature.  Thank!

**Comment by elsesiy** [comment]
@cc-lam We're currently working on it, can't really predict when a stable release will be available..
