### ISSUE TITLE
Is their any way to view default look as weekview.. Not the monthview

### ISSUE THREAD

**Issue by sreeji44** [Mozharovsky/CVCalendar#265]
i asked this same question but no response...CVCalendarView has a func to do exactly that.  public func changeMode(mode: CalendarMode, completion: () -> () = {}) in this function what want to change ?.... 

and one more thing is in the storyborad i want o display it as weekview.. so how can change that also .. please help that will be more helpful for me ...

**Comment by elsesiy** [comment]
Duplicate of #256
