### ISSUE TITLE
Adding more dots per day

### ISSUE THREAD

**Issue by tomvlk** [Mozharovsky/CVCalendar#27]
Maybe an idea to add support for multiple dots per day.

Thanks,
Tom

**Comment by martjemeyer** [comment]
That would be a great addon :)
Also a way to update the dotmarker, when you return from lets say a popover. So you don't have to call commitCalendarViewUpdate() to update the dots. Or is there a more gentle way calling dotMarker(shouldShowOnDayView dayView: CVCalendarDayView) ?

**Comment by Mozharovsky** [comment]
Hello @tomvlk, 

Thank you for the suggested feature. I was thinking about it while working on dots. What stopped me from going this way was that there should be a limit of dots. According to that point it becomes useless since dots are presented for indicating an event on a particular day view. Personally I don't find it useful enough but if you need this feature I will definitely work it out. 

By the way what do you think about personal background color for every day view? With this feature you'll be able to set default background colors not only for all day views but for specific ones. Microsoft's Outlook app contains a calendar with this feature for current day. Let me know what you think about this. 

Regards, 
Eugene

**Comment by tomvlk** [comment]
For me, it would be very nice to see because I'm going to make a 
calendar with multiple type of events. With multiple dots you can see if 
there is an event of a specified type on that day.
So it would be great to have

Thanks,
Tom

**Comment by Mozharovsky** [comment]
Hello @martjemeyer, 

As for committing updates of frames you don't have to call it every time you view is about to appear. Only once. Anyway, I'll fix it in a new release. And relatively your second issue it depends. Do you mean a feature of dynamically changing dots e.g. if a user completes a task and there is no more event on a particular day view? 

Regards, 
Eugene

**Comment by Mozharovsky** [comment]
@tomvlk, 

Then there should be a limit of dots since having extra ones won't make your app looks pretty. In this case I'll add this feature with an upcoming release. Check out repo for updates. 

Regards, 
Eugene

**Comment by tomvlk** [comment]
Thank you :smiley:
:+1: 
Tom

**Comment by martjemeyer** [comment]
Atm for simplicity I press a button and it pops a new view where I can choose a time, duration etc. If I press save, it will set a local notification and dismiss the popup. At that moment I want to add a dot if there isn't any there. But that requires me to update the whole calendar view or swipe a few times over :)

**Comment by Mozharovsky** [comment]
@martjemeyer, 

I got what you mean. That's really important. I've added it to the new release features. Thank you for suggesting such a useful enhancement. 

Regards, 
Eugene

**Comment by martjemeyer** [comment]
Thank you for all your hard work on this great calendar!

**Comment by Mozharovsky** [comment]
Thank you guys for using this software! It makes me keep working on it. Together we build high quality products. :smiley:

**Comment by martjemeyer** [comment]
Thats the plan :D

**Comment by skywinder** [comment]
:+1: +1! If you worry about to many dots, imho - you can limit it with 3 dots it's enough in most cases.

**Comment by thomasbaldwinj** [comment]
Did this feature ever get added? Or have you not been able to get around to it yet? If not, I can work on it and then make a pull request

**Comment by skywinder** [comment]
@thomasbaldwinj it would be nice! :+1:

**Comment by tomvlk** [comment]
@thomasbaldwinj :+1:

**Comment by thomasbaldwinj** [comment]
Alright gentlemen, check out my pull request https://github.com/Mozharovsky/CVCalendar/pull/84. Let me know what you think and if there's a cleaner way you think it can be done, let me know and I'll fix it

@skywinder @tomvlk

**Comment by nanoxd** [comment]
@thomasbaldwinj Your PR assumes that the dots should remain the same shape but a different color. I'm not sure if I'm in the majority, but I feel that it would be more beneficial to make the shape changeable as well. 

For example, let's say you have a way of displaying three different kinds of events on the calendar (birthday shape, circle, and square) and you wanted to display the different shape _if_ an event happened on the date.

**Comment by tomvlk** [comment]
@thomasbaldwinj Seems to be awesome! Didn't test yet, but from seeing screens it lookes great!
Different colors are just my must have!

**Comment by sreeji44** [comment]
when we add event how can we add line on that particular day.... if u tell that it is very helpful ....

**Comment by elsesiy** [comment]
@sreeji44 I don't understand, please rephrase your question.

**Comment by sreeji44** [comment]
i am using this cvcalendar is for add events, display events this all i am using.... when we select the date and add one event i want to display line on that event added day... instead of dot how can i add this...

**Comment by sreeji44** [comment]
@elsesy  i am using this cvcalendar is for add events, display events this all i am using.... when we select the date and add one event i want to display line on that event added day... instead of dot how can i add this...

**Comment by elsesiy** [comment]
@sreeji44 Please open a seperate issue for your request.
