### ISSUE TITLE
how can we remove dots and add lines on that day... instead of dots want to add Lines.. 

### ISSUE THREAD

**Issue by sreeji44** [Mozharovsky/CVCalendar#271]
i dont want dots.. i just want lines on the day... how can i add this?

**Comment by elsesiy** [comment]
@sreeji44 Please have a look at the CVAuxiliaryView class. The property shape of type CVShape allows you to define custom auxiliary views by drawing the desired line with UIBezierPath. If you've further remarks please let us know.

**Comment by sreeji44** [comment]
@elsesiy Ok thankzz i just look that class .. is i want to add new shapes as line... any thing syntax is their for helping me .. plz
