### ISSUE TITLE
How about 'day view' and 'week view' ?

### ISSUE THREAD

**Issue by muratyasarr** [Mozharovsky/CVCalendar#276]
Thanks for this awesome library. Is there a plan for making those(dayview&week view) layouts also a part of CVCalendar? 
Or, if you give some idea on how to build them, it would also be much appreciated.

**Comment by elsesiy** [comment]
@muratyasarr A week view is already available. A day detail view as implemented by apple is currently not in our scope but we might adding such functionality in a future release :) If you've further remarks, please feel free to comment!

**Comment by muratyasarr** [comment]
Wow, thanks for the quick response! :)
But I believe it should be a core feature of the library anyway. ( Because I believe most of the times when users select a day on a calendar, what they want to see is that day's detail view. )
