### ISSUE TITLE
Turn off swipe functionality?

### ISSUE THREAD

**Issue by hsakuli** [Mozharovsky/CVCalendar#277]
Hi I was wondering if there is any way to stop the swiping to switch months/ week functionality. Ive been playing around in the UIScrollViewDelegate and exploring where else I can try to turn this off. Any help would be appreciated!

I would still have buttons below the calendar to get to the next/previous months, I just dont want the user to be able to swipe to a new month.

Thanks,
Lucas

**Comment by patchthecode** [comment]
If you want to stop this functionality, then how do you want to move to other months?

**Comment by zrag123** [comment]
The intended functionality might to be only to display a certain month or the current month?

**Comment by patchthecode** [comment]
@zrag123 why not use boundary dates?

**Comment by hsakuli** [comment]
@patchthecode I have two buttons underneath the calendar that get you to the next/prev months. They call the calendarView.loadNext/PreviousView() functions, exactly like the CVCalendar demo

**Comment by chojunyng** [comment]
I have a same issue, I just changed view Interaction : User Interaction Enabled -> false
So, I can resolve the problem

<img width="287" alt="2016-05-02 4 14 14" src="https://cloud.githubusercontent.com/assets/8664413/14949033/598ebdae-1081-11e6-8135-4a350a9f5edc.png">

**Comment by hsakuli** [comment]
@chojunyng close, but now I can not select a date. I am just looking to turn off the swipe functionality and not anything else

**Comment by mcdappdev** [comment]
Any status on this?

**Comment by hsakuli** [comment]
@mcdappdev I think Ive found a solution. In the CVCalendarContentViewController add the line: 
        scrollView.scrollEnabled = false
into the public init(calendarView: CalendarView, frame: CGRect). This disables the swiping functionality on the calendar, but I can still move to different months through the calendarView.loadNext/PreviousMonth() functions. Hope this helps!

**Comment by mcdappdev** [comment]
@hsakuli Thank you very much!! I appreciate it
