### ISSUE TITLE
CVCalendarView only appearing on iPhone Plus

### ISSUE THREAD

**Issue by Alexis-Bastide** [Mozharovsky/CVCalendar#281]
Hi,

I just did the basic setup to use CVCalendarView:

- connecting the view from the storyboard to my ViewController
- implementing CVCalendarMenuViewDelegate and CVCalendarViewDelegate

```
func presentationMode() -> CalendarMode {
        return .MonthView
    }
    
    func firstWeekday() -> Weekday {
        return .Monday
    }
    
    override func viewDidLayoutSubviews() {
        super.viewDidLayoutSubviews()
        
        calendarView.commitCalendarViewUpdate()
        menuView.commitMenuViewUpdate()
    }
```

 it's appearing properly on iphone 6/6S plus, but when I am trying on smaller iphones (6 or 5) the view doesn't appear.

Here are some screenshots :

<img width="1680" alt="capture d ecran 2016-04-25 a 11 10 06" src="https://cloud.githubusercontent.com/assets/11092228/14779233/79420fca-0ad7-11e6-95a7-327c0766f574.png">
<img width="1680" alt="capture d ecran 2016-04-25 a 11 11 05" src="https://cloud.githubusercontent.com/assets/11092228/14779239/7d3a75d6-0ad7-11e6-9c6f-ecea31ff96e0.png">
<img width="1680" alt="capture d ecran 2016-04-25 a 11 11 38" src="https://cloud.githubusercontent.com/assets/11092228/14779241/7ecf7414-0ad7-11e6-828f-713ab1de491e.png">
<img width="1680" alt="capture d ecran 2016-04-25 a 11 12 47" src="https://cloud.githubusercontent.com/assets/11092228/14779242/8097db42-0ad7-11e6-8ac8-9af881f86b63.png">

What am I doing wrong ?

**Comment by Alexis-Bastide** [comment]
I couldn't find a way to fix that so I used FSCalendar instead

**Comment by patchthecode** [comment]
Is FS calendar good for you? or do you think it is not customizable enough?
