### ISSUE TITLE
Possibility to set the selected date

### ISSUE THREAD

**Issue by Nitner0C** [Mozharovsky/CVCalendar#283]
I haven't been able to figure out how to set the selected date manually.

In my case I'd like to be able to handle a swipe gesture in another view to change the day displayed in my CVCalendarView.

If anyone has figured it out, I'd be happy.

Thanks
Corentin

**Comment by Kastr** [comment]
Hi, I guess this is what you need:

`
var calendarView:CVCalendarView? //init somewhere
func changeDay(nDate:NSDate) {
        self.calendarView.toggleViewWithDate(nDate)
    }`

**Comment by Nitner0C** [comment]
Perfect! Thank you!

**Comment by Nitner0C** [comment]
I have kind of a problem...
I always have a week view, and when I toggle to a date that is in the next week, it doesn't change the week view...

**Comment by elsesiy** [comment]
@Nitner0C please open a new issue.
