### ISSUE TITLE
How to set current day label unselected color?

### ISSUE THREAD

**Issue by ridvank** [Mozharovsky/CVCalendar#290]
I am trying to set the current day label background color to something when it is not selected. However i could not see any delegate method for that. Any help would be appreciated.

**Comment by James-Coleman** [comment]
It's dayLabelPresentWeekdayTextColor for anyone else finding themselves here.

**Comment by IsmailAhmedIsmail** [comment]
@James-Coleman He is asking about Background Color, not the text color itself.
