### ISSUE TITLE
DaotMarker Color

### ISSUE THREAD

**Issue by sreeji44** [Mozharovsky/CVCalendar#291]
DotMarker Color date selected color is whiteColor. But non selected date color is Black.. How can i change that color?.... plz reply

**Comment by elsesiy** [comment]
Closed since the issue is not conforming to the template provided.

**Comment by sreeji44** [comment]
@elsesiy  why u are saying that it is not conforming the template ?...  that is my requirement. which i am using your library you have at least answer ...

**Comment by elsesiy** [comment]
It means you should've used the provided issue template to ask your question instead of the way you did. It's too much work to ask for more details, point to similar issues, etc.
