### ISSUE TITLE
I want to select multiple dates on an urgent basis. Please help me.

### ISSUE THREAD

**Issue by RIju912** [Mozharovsky/CVCalendar#294]
- [x] I have verified there are no duplicate active or recent bugs, questions, or requests
- [x] I have verified that I am using the latest version of CVCalendar.
- [x] I have given my issue a non-generic title.

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used (Cocoapods spec):
* Device used i.e. iPhone 6S:
* Physical device (y/n):
* Link to your project (if available):

**Comment by TAIIOK** [comment]
`public func performDayViewSingleSelection(dayView: DayView) 
`
Fix this  for themselves

**Comment by TAIIOK** [comment]
example for you 

selectionSet contains selected days so you can get days  but  days are not current its  previous
`    public func performDayViewSingleSelection(dayView: DayView) {
        
        if (selectionSet.contains(dayView))
        {
        presentDeselectionOnDayView(dayView)
        selectionSet.remove(dayView)
        }
            
        else{
        selectionSet.insert(dayView)
        
        if selectionSet.count > 1 {
            for dayViewInQueue in selectionSet {
                if dayView != dayViewInQueue {
                    if dayView.calendarView != nil {
                        //presentDeselectionOnDayView(dayViewInQueue)
                        
                    }
                    
                }
                
            }
        }
        
        if let _ = animator {
            if selectedDayView != dayView {
                selectedDayView = dayView
                presentSelectionOnDayView(dayView)
            }
        }
        }
    }`

**Comment by RIju912** [comment]
I want to long press on a date(say 26th May) one pop up will show that you have to select the date range, after user will see the pop up user will see another date (say 30th May), and the as a result the range will get selected( from 26 to 30 th May , with a different color). How will I do that? Please help.

**Comment by TAIIOK** [comment]
use my example and add some var to detect current selection type 
See an array (selectionSet) with dates and then select them using toggle function

**Comment by RIju912** [comment]
your example? Please elaborate!

**Comment by RIju912** [comment]
Or I will tap one date and tap on another date. like I am tapping on 5th and again tapping on 15th. total will get selected.and if dont want to select 10th and 12th I will double tap on that. but the rest of the range will get selected. How will I do this @TAIIOK

**Comment by elsesiy** [comment]
@TAIIOK pointed you in the right direction, thus closed.
