### ISSUE TITLE
Cant import CVCalendar

### ISSUE THREAD

**Issue by RaymondMoay** [Mozharovsky/CVCalendar#296]
Hi! I have no idea what's going wrong with my pod install.

My Podfile: 

`# platform :ios, '9.0'

target 'Streak' do
 
  use_frameworks!
  pod 'CVCalendar', '~> 1.2.9'

end
`
I can attach the CVCalendar classes through storyboard, but I can't seem to import CVCalendar. Any help is much appreciated!

**Comment by elsesiy** [comment]
Have you figured it out? If not, I'll reopen.
