### ISSUE TITLE
Init CVCalendar with a specific day in current month

### ISSUE THREAD

**Issue by FabIcar** [Mozharovsky/CVCalendar#30]
I have a problem when i'm instantiate cvcalendar 2 times or more . After the second time I lost the top marker on current day and didSelectDayView() is not called
Overall I can't instantiate cvcalendar with top marker on specific day in the same visible month. Is it possible? 
toggleMonthViewWithDate() works only if I'm not in the current month. It will be great if we can select a day by code with a date in parameter

**Comment by Mozharovsky** [comment]
Hello @FabIcar, 

The issue you've reported is in the TODO list of things coming in the upcoming release. Check out #28 thread to find more details to come. As for returning to current day it basically works only if the presented week or month view is not equal to the current one. Actually I can implement toggling to current date if you're not selecting one if it makes a sense for you. So let me know. 

Regards, 
Eugene

**Comment by FabIcar** [comment]
I Think the only feature I need at this moment is to select a specific day by code :)
Good job by the way
