### ISSUE TITLE
I tried to install using cocoapod like in the documentation, but it gets stuck and just stuck. Is there any new way to add this library?? 

### ISSUE THREAD

**Issue by krazziekay** [Mozharovsky/CVCalendar#301]
- [ ] I have verified there are no duplicate active or recent bugs, questions, or requests
- [ ] I have verified that I am using the latest version of CVCalendar.
- [ ] I have given my issue a non-generic title.

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used (Cocoapods spec):
* Device used i.e. iPhone 6S:
* Physical device (y/n):
* Link to your project (if available):

**Comment by elsesiy** [comment]
Just tried it again and it works flawlessly. Probably it was a temporary problem, so please try again and reopen if the issue persists.
