### ISSUE TITLE
How can i grey out custom dates in a fast and efficient way, it would be nice to have this feature, i added a delegate to check the dayView for days and grey out those days, I also would like to have no user interaction on the grey out dates

### ISSUE THREAD

**Issue by aderhartunian** [Mozharovsky/CVCalendar#304]
- [ ] I have verified there are no duplicate active or recent bugs, questions, or requests
- [ ] I have verified that I am using the latest version of CVCalendar.
- [ ] I have given my issue a non-generic title.

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used (Cocoapods spec):
* Device used i.e. iPhone 6S:
* Physical device (y/n):
* Link to your project (if available):

**Comment by arbidh** [comment]
never mind i figured it out

**Comment by kerimsari** [comment]
Hi arbidh,

Could you please explain how you figued it out?

Kerim
