### ISSUE TITLE
Past days greyed out?

### ISSUE THREAD

**Issue by kerimsari** [Mozharovsky/CVCalendar#309]
Hello guys,

I am using the latest version of CVCalendar....

My goal is to make pas days text color different than today and future days?
Do you know how can i achieve that with CVCalendar?

Please suggest..
Thanks

Kerim

**Comment by SHADOOOO** [comment]
@Mozharovsky

**Comment by kerimsari** [comment]
Hi Shadoooo,

I didnt get the answer?

Thanks

**Comment by SHADOOOO** [comment]
I'm facing the same issue, i'm trying to make days before today disabled or at least change their text color to look as if they were disabled, i really hope there's a way to do that 

Thanks

**Comment by elsesiy** [comment]
Please take a look at the provided example app. Past days are greyed out by default and can be toggled invisible if you want them to disappear...

**Comment by SHADOOOO** [comment]
Thanks a lot for your reply, i meant by past days any day before today (for example, yesterday and days before text color to be grey). i wanted to change their text color or selection background color, is that possible? 

and is it possible to make the calendar display only current and following months? (not the past month)

Thanks again,

**Comment by elsesiy** [comment]
Please open two new issues with respect to the provided issue template and someone will help you :)
