### ISSUE TITLE
Labels for all the dates repeatedly getting darker with each frame update on viewDidAppear on projects with uitabbarcontrollers

### ISSUE THREAD

**Issue by Somnibyte** [Mozharovsky/CVCalendar#31]
I currently have a project that implements UITabBarController. I placed my calendar in one of the tabs. Ever time I go back to the calendar, all the labels for the dates seem to be getting more darkened as if more dates are spawning on-top of existing dates. I looked over at my memory and each time I would go back to the tab containing the calendar the memory would increase about 1 MB each visit, once it got to a certain point swiping would appear to be sluggish. The "darkening" effect only occurs whenever I go back to the tab multiple times, I identify the behavior when the console says "Updating 1".

**Comment by Somnibyte** [comment]
I think this is related to issue #22. This thread may be closed.

**Comment by Mozharovsky** [comment]
Hello @Somnibyte, 

CVCalendar shouldn't be rendered twice within your app. It'll be fixed in the coming release. As for now you can simply check if it has already been rendered and don't do it again.  

```swift
  var rendered = false 
  override func viewDidAppear(animated: Bool) {
        super.viewDidAppear(animated)
        
        if !rendered {
              self.calendarView.commitCalendarViewUpdate()
              self.menuView.commitMenuViewUpdate() 
              rendered = true 
        }
    }
```

**Comment by Somnibyte** [comment]
Thank you so much @Mozharovsky. I look forward to the newest version, but so far it's an amazing calendar.

**Comment by Mozharovsky** [comment]
We've already discussed the solution but let it be here anyway. 

Simply move the commitment of changes to `viewDidLayoutSubviews` method. 

```swift
    override func viewDidLayoutSubviews() {
        super.viewDidLayoutSubviews()
        
        calendarView.commitCalendarViewUpdate()
        menuView.commitMenuViewUpdate()
    }
```
