### ISSUE TITLE
Disable or Change Past Days text color or selection background color

### ISSUE THREAD

**Issue by SHADOOOO** [Mozharovsky/CVCalendar#311]
Hello everyone,

I am using the last version of CVCalendar, when i added the calendar view to my app i expected that i will be able to customize the Text Color or the selection background color of past days, like for example, i want to change the text color of yesterday and the days before that to grey or change their selection background color. in the current version i couldn't find anything that could help me achieve this, is it possible to add a function, so we can customize the color or the selection background color and the specific days we want those changes to be applied?

Thanks,

**Comment by elsesiy** [comment]
Issue template?
