### ISSUE TITLE
Error when using CVCalendar library with Xcode 8 bet and Swift 3.0

### ISSUE THREAD

**Issue by CIsOnTop** [Mozharovsky/CVCalendar#314]
Updated the CVCalendar library with pods to version 2.2.5 and when i am compiling in xcode 8 beta it gives error that code needs to converted to Swift 3.0.

Can you let us know if the CVCalendar library has been ported to Swift 3.0 or not.

**Comment by elsesiy** [comment]
It hasn't yet and it won't in the near future. Feel free to make the changes and submit a PR :)

**Comment by blwinters** [comment]
From what I can see, one of the biggest conflicts with Swift 3 is `public typealias Date = CVDate` in CVCalendarView.swift. Swift 3 removed the NS predicate so `NSDate` is now `Date`, so the typealias needs to be removed and all of its instances updated.

**Comment by elsesiy** [comment]
I've too much on plate right now, might do it towards the end of the year. If it's urgent, please make the changes and submit a PR.

**Comment by probugtivity** [comment]
Hi, i am using CVCalendar as well in my app. It worked great till this morning, i converted to swift3!. Is there a workaround for swift3 then? If anyone has figured this, please let me know!

Thanks

**Comment by CIsOnTop** [comment]
Hello,

I forked And added a Swift 3.0 because I couldn't figure out how to create a proper pull request. But I uploaded my Swift 3.0 version its been working great. Took awhile but finally got it working and I've been using it while beta testing. I hope it works for you, let me know! 

Thank you,

Christian Valderrama

**Comment by elsesiy** [comment]
Please see #339, library is now compatible with Swift 3.

**Comment by CIsOnTop** [comment]
I just created a pull request for my fork. 

Thank You,

Christian Valderrama

**Comment by probugtivity** [comment]
Spectacular!...thanks... let me give it a shot
