### ISSUE TITLE
I need to implement calendar view like Activity app with activity ring under every day. 

### ISSUE THREAD

**Issue by mecid** [Mozharovsky/CVCalendar#315]
I need to implement calendar view like Activity app with activity ring under every day. 
Can i implement this with CVCalendar?

**Comment by elsesiy** [comment]
Issue Template?

**Comment by mecid** [comment]
@elsesiy this is not issue, this is question.

**Comment by elsesiy** [comment]
@mecid An issue template is not solely restricted to actual issues ;) It's meant to be included in every question/issue posed so you can proof your work and save us a lot of time.

**Comment by mecid** [comment]
@elsesiy ok, i will use it next time. But can you help me with my question?

**Comment by mecid** [comment]
@elsesiy Can i use CVCalendar to create screen like this.
I need to show activity ring under every day.

![network-brianna-apple-watch-activity](https://cloud.githubusercontent.com/assets/324372/16765262/1dc58028-4844-11e6-9811-98c21a7f419b.jpg)

**Comment by mecid** [comment]
@elsesiy i see you implement this feature in develope_2.0 branch, but i cant build 2.0 version. I have multiple errors.

**Comment by elsesiy** [comment]
@mecid Yeah you're right but I won't finish it sometime soon..
