### ISSUE TITLE
Get start and end date for Month and week respectively for both mode 

### ISSUE THREAD

**Issue by srinivasanVaradan** [Mozharovsky/CVCalendar#317]
I request you to point me , where can i get the start and end date for Month . the same for week view.

WeekView:
i tried to get the startDate and EndDate for the current week, i use didSelectDayView delegate by navigating through dayView.weekView.dayViews[cvcalendarDayView].date.date.    how do i get start and end date for a week and same also month view

**Comment by amirhosseinakhoondzadeh** [comment]
I also stuck in getting first and end of each month in the calendar.

**Comment by elsesiy** [comment]
@srinivasanVaradan @amirhosseinakhoondzadeh Please use the issue template.
