### ISSUE TITLE
How to init a date in one specific month when I calendar show up?

### ISSUE THREAD

**Issue by Huy-Vu** [Mozharovsky/CVCalendar#318]
## Expected Behavior
I have a Date in advance and want to show that date as a selected date on calendar when I come to calendar view

## Current Behavior
Only able show the current month

**Comment by Rashesh-Bosamiya** [comment]
Following line of code would select the date you pass.

`calendarView.toggleViewWithDate(NewDate)
`
make sure about the date format it takes.

Generally it is `"yyyy-MM-dd HH:mm:ss Z"`

**Comment by elsesiy** [comment]
@Rashesh-Bosamiya got it right, if you've further remarks @Huy-Vu please let me know!
