### ISSUE TITLE
Reload calendar data

### ISSUE THREAD

**Issue by rgalante** [Mozharovsky/CVCalendar#320]
I´m working on an application which get events from a third party. So once I get that, I need to have the delegate methods once I retrieve the information from the server, so I can mark the days using this delegate method: 

func dotMarker(shouldShowOnDayView dayView: CVCalendarDayView) -> Bool

Is there any way to make all the delegate methods to run again? I can´t find a proper way to do it. 

Thanks!

**Comment by rabehssera** [comment]
You should call : 

self.calendarView.contentController.refreshPresentedMonth()

**Comment by rgalante** [comment]
Thanks @rabehssera. That did it!
