### ISSUE TITLE
how can we navigate  different date now it is loading currentdate. 

### ISSUE THREAD

**Issue by sreeji44** [Mozharovsky/CVCalendar#326]
how can we load different date now it is loading current date. Every time i load it starts with current date. For example today is 22 august 2016 i just created a event on 25 august 2016. so after creating event i just want to navigate to 25 august 2016.  is their any way to navigate like this?...

**Comment by Rashesh-Bosamiya** [comment]
means, you want initial highlighted selection of date on particular date that you choose?

**Comment by sreeji44** [comment]
@Rashesh-Bosamiya :) ya i need to choose particular date :)

**Comment by zuaaef** [comment]
[This](https://cocoapods.org/pods/JTAppleCalendar)

**Comment by Rashesh-Bosamiya** [comment]
I am looking for the same.
Other participants please help us.

**Comment by Rashesh-Bosamiya** [comment]
Hello,
 
I finally managed to get the solution.

All you need to do is just write the following line of code.

`calendarView.toggleViewWithDate(NewDate)`

Example:

Initially when calendar loads, the selected date is whatever the current date is. Now if you want to initially select tomorrow date. then,

```
let today = NSDate()
        let tomorrow = NSCalendar.currentCalendar()
        .dateByAddingUnit(.Day, value: 1, toDate: today, options: [])
        
        calendarView.toggleViewWithDate(tomorrow!)
```

Make sure about the date format `toggleViewWithDate` is take.
