### ISSUE TITLE
How to add events to month view & reload the monthview ?

### ISSUE THREAD

**Issue by YogeshBharate** [Mozharovsky/CVCalendar#328]
@Mozharovsky Hi ..

First of all thanks you for such wonderful library !!! I am using CV Calendar view in my iPad application. In my application, gets the appointments using RESTful API, but when actual data gets, the delegates methods has been called. How to add events or array of events into month view ? And how to reload the month view ? Thank in advance !!!!

**Comment by Rashesh-Bosamiya** [comment]
In order to reload monthView you need to write following line.

`calendarView.contentController.refreshPresentedMonth()`

**Comment by elsesiy** [comment]
Thanks @Rashesh-Bosamiya for helping others out. I'll close this issue for now, @YogeshBharate if you've further remarks please comment.
