### ISSUE TITLE
Nib Files and @IBDesignable

### ISSUE THREAD

**Issue by asafall** [Mozharovsky/CVCalendar#329]
Hi,
First of all, I've tried to read your code but it was unreadable.
What I mean is I almost can't understand how it works.
I recommend you to organize your code, and by that I recommend you to use nib files for design the views instead to write the design in coding.

Moreover, you can use the @IBDesignable keyword to see the calendar strate on the storyboard.

And please stop using **a lot** in typealias, that makes the code less unreadable.

Thanks for the attention.

**Comment by zuaaef** [comment]
Hmm.. you can always look up one thats more readable.

**Comment by elsesiy** [comment]
I must second @zuaaef. The primary goal of this library is to provide a clean API which is a work-in-progress mission. If you've actual questions about the functionality, go ahead and ask. We're well aware of IBDesignables but haven't had the time to fully migrate the library to support AutoLayout properly.
