### ISSUE TITLE
Text Label Color for Unselected Dates

### ISSUE THREAD

**Issue by iChauster** [Mozharovsky/CVCalendar#334]
- [x] I have verified there are no duplicate active or recent bugs, questions, or requests
- [x] I have verified that I am using the latest version of CVCalendar.
- [x] I have given my issue a non-generic title.

## Expected Behavior
I've tried all of the CVCalendarViewAppearanceDelegate Methods with changing calendar text color, none of which gives the desired effect. 

I would like to have the default text (all the numbers on the calendar) be white. However, none of the delegate methods actually do this, except after the date is selected and unselected again.

![screen shot 2016-09-03 at 9 37 41 pm](https://cloud.githubusercontent.com/assets/7015374/18228493/b42f2ac4-721e-11e6-9e19-8fce356e1fda.png)

## Current Behavior
Here, I set the default text color to blue, but the text only appears after a date has been selected. I expected all the dates to be in blue, however after attempting to reload the calendar view and "commitingCalendarUpdates", the default text color is still black.

I'm not quite sure if this is what the delegate method aims to do, but it seems I cannot set text colors until after they are clicked on.
 `
func dayLabelColor(by weekDay: Weekday, status: CVStatus, present: CVPresent) -> UIColor? {

        return UIColor.whiteColor()
      
        //still get the same black text color, but only changes to white after the date has been selected
 }
`
I also tried all the other delegate methods and ensured the calendar views were updating.
## Context
I'm trying to change the default text to fit my design scheme. The Weekday labels on the CVCalendarMenuView can be changed easily, but the default text on the CVCalendarView is giving me serious migraines.

## Your Environment

* Version used (Cocoapods spec): 1.3.0
* Device used : XCode Sim.
* Physical device (y/n): N
* Link to your project (if available): N/A

Thank you for your time, I've been searching for similar issues but many of them are either unanswered or have solutions that don't fix the bug.

**Comment by iChauster** [comment]
Issue fix : everything works correctly now. 

I fixed this issue by getting the order of delegate declaration correct.

This issue occurs when the 'calendarAppearanceDelegate' is declared after the 'calendarDelegate', which causes some initialization issues. However, after declaring the 'calendarAppearanceDelegate' first, everything works as planned.

**Comment by manjuhere** [comment]
how were you able to get few selected dates to blue. I want to be able to highlight a few dates in a color before/when calendar view loads.
