### ISSUE TITLE
dotMarker Show wrong date match , How to fix?

### ISSUE THREAD

**Issue by paneaktae** [Mozharovsky/CVCalendar#335]
- [ ] I have verified there are no duplicate active or recent bugs, questions, or requests
- [ ] I have verified that I am using the latest version of CVCalendar.
- [ ] I have given my issue a non-generic title.

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used (Cocoapods spec):
* Device used i.e. iPhone 6S:
* Physical device (y/n):
* Link to your project (if available):

When i set value date Example 2016-09-28 is Matching but Dot marker show on date 29 on Calendar View. Please Help me Thx.

**Comment by elsesiy** [comment]
Use the Issue Template
