### ISSUE TITLE
Problem with the last update!!!

### ISSUE THREAD

**Issue by schulz89sp** [Mozharovsky/CVCalendar#336]
Hi, til the last CVCalendar update he was fine, with the last returned instead I XCode error ...

"Fatal error: unexpectedly found nil value while unwrapping an Optional"
The offending line is this:
let data = dateformatter.stringFromDate (dayView.date.convertedDate ()!)

When I open the calendar no problem occurs when I change the month.
I did not touch anything, just updated the CVCalendar folder.

Help me please!

**Comment by elsesiy** [comment]
Use the Issue Template
