### ISSUE TITLE
Change the month and the app goes in crash!!!

### ISSUE THREAD

**Issue by schulz89sp** [Mozharovsky/CVCalendar#337]
- [Y] I have verified there are no duplicate active or recent bugs, questions, or requests
- [Y] I have verified that I am using the latest version of CVCalendar.
- [Y] I have given my issue a non-generic title.

## Expected Behavior
When I open the calendar should then change the month if required

## Current Behavior
The app crashes when I change the month

## Possible Solution
I have no idea

## Steps to Reproduce (for bugs)
1. I open the calendar and everything works, the days vengoni circled and everything is ok
2. Change the month and the app goes in crash
3. It returns this error in the "func supplementaryView (shouldDisplayOnDayView dayview: DayView)": "Fatal error: unexpectedly found nil value while unwrapping an Optional"
The offending line is: let dateformatter NSDateFormatter = ()
dateformatter.dateFormat = "dd / mm / yyyy"
let data = dateformatter.stringFromDate (dayView.date.convertedDate ()!)
Where "Date" = "" to the compiler

## Context
Should function with that circle the days that have events, as soon as I open the calendar happens!

## Your Environment
I did not touch anything, just updated the CVCalendar folder.

**Comment by nikolay-dementiev** [comment]
Hello.

I just built a Demo application and another application "from scratch" - and I have not found an application bugs

Tell more about your problem.
And, if possible, give access to your project (the part that produces an error - the rest of the code - not needed - so you can remove it - if you need it)

**Comment by schulz89sp** [comment]
func supplementaryView(shouldDisplayOnDayView dayView: DayView) -> Bool {
                let dateformatter = NSDateFormatter()
                dateformatter.dateFormat = "dd/MM/yyyy"
                let data = dateformatter.stringFromDate(dayView.date.convertedDate()!)
                let dataString = "06/09/2016"
                if (data == dataString) {
                    return true // color circles
                }
        }
        return false  // not those circles
    }

When I open the calendar and it gives me the current month are circles and if the mold:
print (date) in console comes out:
01/09/2016
09/02/2016
09/02/2016
09/03/2016
09/03/2016
04/09/2016
04/09/2016
05/09/2016
05/09/2016
06/09/2016
09/07/2016
....
When I change the month gives me the error:
fatal error: unexpectedly found nil value while unwrapping an Optional
Data = "" and no more:
01/10/2016
02/10/2016
02/10/2016
10/03/2016
....

Crash because not having the variable "Data" this can not be compared with "dataString"

**Comment by schulz89sp** [comment]
If you give me your email, I send the project

**Comment by nikolay-dementiev** [comment]
you can share your part of a project with an error on my google drive: https://drive.google.com/drive/folders/0B1sCn25bPLwrc2ZvWXhJYzNHN3M

**Comment by schulz89sp** [comment]
I sent a sample app that I use as proof!
Just open it works, how change month crash ...
The app I use more or less does the same thing ...

**Comment by nikolay-dementiev** [comment]
Before you update CVCalendar, which version of it worked fine?

**Comment by nikolay-dementiev** [comment]
have you a copy of that version of your program?

**Comment by schulz89sp** [comment]
I sent you the files!!

**Comment by nremarck** [comment]
I have the same problem, in fact this issue is coming in the initialization phase.

In **CVCalendarDayView.init**
public init(weekView: CVCalendarWeekView, weekdayIndex: Int) {
        self.weekView = weekView
        self.weekdayIndex = weekdayIndex
        
        
        if let size = weekView.calendarView.dayViewSize {
            let hSpace = weekView.calendarView.appearance.spaceBetweenDayViews!
            let x = (CGFloat(weekdayIndex - 1) * (size.width + hSpace)) + (hSpace/2)
            super.init(frame: CGRect(x: x, y: 0, width: size.width, height: size.height)) <- Call
        } else {
            super.init(frame: CGRect.zero)
        }

date is initialized there AFTER the super.init call
date = dateWithWeekView(weekView, andWeekIndex: weekdayIndex)

The _super.init_ call _supplementarySetup_ because a _didSet_ is implemented

public override var frame: CGRect {
        didSet {
            if oldValue != frame {
                selectionView?.setNeedsDisplay()
                topMarkerSetup()
                preliminarySetup()
                **supplementarySetup()**
            }
        }
    }

An _supplementatrySetup_ failed because date is nil.
In fact initialized later, that's why the code is working correctly if you don't try to used "date" into the _supplementarySetup()_ method.

**Comment by schulz89sp** [comment]
I solved ... maybe!

    func supplementaryView(shouldDisplayOnDayView dayView: DayView) -> Bool {
        let dateformatter = NSDateFormatter()
        dateformatter.dateFormat = "dd/MM/yyyy"//"yyyy-MM-dd"
        let date2 = dateformatter.stringFromDate(dayView.date.convertedDate()!)
        if ((datestringarray.count !=0) && (dayView.date != nil)) {  // <--- dayView.date != nil
            for(var i=0;i<datestringarray.count;i++)
            {
                if(date2==datestringarray[i])
                {
                    return true
                }
            }
        }
        return false
    }

So it works!

**Comment by nikolay-dementiev** [comment]
Fix your mistake - it's good! 

We need a little bit to understand - why it all occurred - most likely, there is some kind of bug in the CVCalendar's code

**Comment by schulz89sp** [comment]
Yes, because in the previous version, even without putting my fix, the app does not crashed!
Thanks anyway!

**Comment by nremarck** [comment]
Did you see my latest comments ?

The problem occured because the _didSet_ on frame: CGRect implies a side effect.

The _CVCalendarDayView.init_ call the _super.init(frame: CGRect(x: x, y: 0, width: size.width, height: size.height))_ and didSet who call _supplementarySetup()_ with a date not yet initialized.

**Comment by nremarck** [comment]
Your welcome ...
Congratulation for your very nice calendar :-)

Envoyé de mon iPhone

**Comment by elsesiy** [comment]
@nikolay-dementiev Feel free to submit a PR :)

**Comment by nikolay-dementiev** [comment]
elsesiy, I just created the PR#346, please check it
nremarck, you are awesome. teach me © ))

**Comment by elsesiy** [comment]
Just merged, thus closed.

**Comment by nikolay-dementiev** [comment]
Thank you
