### ISSUE TITLE
Appearance Doesn't update for the next and previous months

### ISSUE THREAD

**Issue by anthonycastelli** [Mozharovsky/CVCalendar#34]
When using the `CVCalendarViewAppearanceDelegate` to set the label text color and so forth, swiping to the next or previous doesn't reflect those changes. Once I swipe to the following month and then swipe back, then they are updated. Am I not implementing something? If possible, can you look into this ASAP? I have an app this is close to be finalized and I would like to have this fixed before I submit it for review.

Thanks a million!

**Comment by Mozharovsky** [comment]
Hello @anthonycastelli, 

This issue will be fixed in the new release version. It will be available in the beginning of April. 

Thank you for reporting!

Regards, 
Eugene

**Comment by anthonycastelli** [comment]
Awesome! Thank you so much!

**Comment by anthonycastelli** [comment]
Any progress on this yet?

**Comment by FrancisBaileyH** [comment]
@anthonycastelli, I'm not sure if you had solved your issue yet through other means, but I ran into this issue as well and just edited the UIColor properties directly in the CVCalendarViewApperance.swift file, in case you were looking for a quick fix.

**Comment by Mozharovsky** [comment]
Hello @anthonycastelli, 

The pre-release version fixes this issue. You can find it [here](https://github.com/Mozharovsky/CVCalendar/releases/tag/1.1.0). 

Let me know if it works for you so I can close the issue. 

Regards, 
Eugene

**Comment by anthonycastelli** [comment]
@FrancisBaileyH What were the properties you modified? I quickly looked at it, but never found the right properties. 

@Mozharovsky Let me give that shot!

**Comment by anthonycastelli** [comment]
@Mozharovsky That did seem to fix the color issue I had. Nice work on the new rewrite too. Seems a bit cleaner, easier to understand. :+1:
