### ISSUE TITLE
Programmatically Reloading the Calendar

### ISSUE THREAD

**Issue by ozgur** [Mozharovsky/CVCalendar#340]
- [x] I have verified there are no duplicate active or recent bugs, questions, or requests
- [x] I have verified that I am using the latest version of CVCalendar.
- [x] I have given my issue a non-generic title.

I couldn't find a method that programmatically reloads current view (month or week content controller depending on calendar mode). Is there a way to do that? 

In my project, I am making an HTTP request to get all calendar events and using the data API returns, I decide whether or not I should show the dot markers.

Same flow like:

1) Initialize a table view
2) Make an asynchronous request to some remote resource
3) update your data source with the data fetched and then call `tableView.reloadData`.

Thanks.

**Comment by ozgur** [comment]
can it be `calendarView.contentController.refreshPresentedMonth()`?

**Comment by elsesiy** [comment]
@ozgur Exactly, `refreshPresentedMonth` is meant to be used for refreshing contents.

**Comment by ozgur** [comment]
@elsesiy gpt it thanks!
