### ISSUE TITLE
How to change Year?

### ISSUE THREAD

**Issue by paneaktae** [Mozharovsky/CVCalendar#345]
how to change year? thx

**Comment by elsesiy** [comment]
Please use Issue Template.

**Comment by moosa0709** [comment]
what does it mean please use issue template?

**Comment by elsesiy** [comment]
It means don't delete the prefilled form when submitting a new issue but actually adhere to what information you should provide in order to have others help you out.

**Comment by kutakmir** [comment]
https://github.com/CVCalendar/CVCalendar/issues/431

:)
