### ISSUE TITLE
Not Working on ios 7

### ISSUE THREAD

**Issue by dev-ajmehra** [Mozharovsky/CVCalendar#35]
this library is not working in ios 7 devices

**Comment by yaronlevi** [comment]
For me it works without any problem in ios 7

**Comment by dev-ajmehra** [comment]
i crashes in window 7 devices

**Comment by Mozharovsky** [comment]
Hello @dev-ajmehra, 

Thank you for the report. 

Frankly saying I can't test CVCalendar on an iOS 7 based device. It supports iOS 7+ so it should work. Maybe something is wrong with setup or any hidden bug. Please let me know what is wrong. It'd be also great if you attached images showing the issue. 

Regards, 
Eugene

**Comment by dev-ajmehra** [comment]
hello @Mozharovsky 
Sorry for the late reply
i was not in the touch with my laptop since last week .
when ever is get some free time i will attach the screen shot as well as
Regard
Aj Mehra

**Comment by Mozharovsky** [comment]
CVCalendar now supports iOS 8 and above.
