### ISSUE TITLE
Error in swift 3.0

### ISSUE THREAD

**Issue by sonysum** [Mozharovsky/CVCalendar#350]
im using swift 3.0 Xcode 8.0
i have an Error:
“Use Legacy Swift Language Version” (SWIFT_VERSION) is required to be configured correctly for targets which use Swift. Use the [Edit > Convert > To Current Swift Syntax…] menu to choose a Swift version or use the Build Settings editor to configure the build setting directly.

**Comment by elsesiy** [comment]
Please elaborate on the error by using the provided issue template. I can't help anybody without being able to reproduce the issue...

**Comment by elsesiy** [comment]
Is this still an issue?

**Comment by bdparrish** [comment]
I don't believe it is.  If you are using the current version, then Xcode automatically wants to update CVCalendar to Swift 3.  The code is already updated for Swift 3 though.  Once you do Edit > Convert... then you can build the project when added with CocoaPods.

**Comment by elsesiy** [comment]
@bdparrish Thank you for letting me know. It's weird because I just checked did a clean setup with the pod and haven't had that problem. Anyway, seems to be resolved -> closed.
