### ISSUE TITLE
 MORE THAT A PROBLEM IS A QUESTION ON THE PROCEDURE CVCALENDAR

### ISSUE THREAD

**Issue by schulz89sp** [Mozharovsky/CVCalendar#353]
public override var frame: CGRect {
        didSet {
            if oldValue != frame {
                selectionView?.setNeedsDisplay()
                topMarkerSetup()
                preliminarySetup()
		if date != nil {
		   supplementarySetup()
		}
            }
        }
}

    public init(weekView: CVCalendarWeekView, weekdayIndex: Int) {
        self.weekView = weekView
        self.weekdayIndex = weekdayIndex

        if let size = weekView.calendarView.dayViewSize {
            let hSpace = weekView.calendarView.appearance.spaceBetweenDayViews!
            let x = (CGFloat(weekdayIndex - 1) * (size.width + hSpace)) + (hSpace/2)
            super.init(frame: CGRect(x: x, y: 0, width: size.width, height: size.height))
        } else {
            super.init(frame: CGRect.zero)
        }

        date = dateWithWeekView(weekView, andWeekIndex: weekdayIndex)
        
        interactionSetup()
        labelSetup()
        setupDotMarker()
        topMarkerSetup()

        if frame.width > 0 {
            preliminarySetup()
            supplementarySetup()
        }

        if !calendarView.shouldShowWeekdaysOut && isOut {
            isHidden = true
        }
}

These two methods are performed in the "CVCalendarDayView.swift" file, in particular the methods:
preliminarySetup ()
supplementarySetup ()
Why they are launched from here?
If then I toss them in viewController.swift files will make him do twice the same shift, do not you think?
I in my project, I eliminated them, in my opinion should only be implemented at the discretion of that program, right?
If we have other functions please spiegarmele if you can.
Thank you!

**Comment by elsesiy** [comment]
Please use the issue template.
