### ISSUE TITLE
swift 2.3 support

### ISSUE THREAD

**Issue by JackNova** [Mozharovsky/CVCalendar#357]
- [x] I have verified there are no duplicate active or recent bugs, questions, or requests
- [x] I have verified that I am using the latest version of CVCalendar.
- [x] I have given my issue a non-generic title.

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Context

Are you planning to release a version for the swift 2.3 compiler? 

## Your Environment

* Version used (Cocoapods spec):
* Device used i.e. iPhone 6S:
* Physical device (y/n):
* Link to your project (if available):

**Comment by elsesiy** [comment]
You obviously didn't check recent issues as you assured, since #349 is dealing with the very same question.

**Comment by JackNova** [comment]
I'm sorry, I didn't check on closed issues
