### ISSUE TITLE
Updating to iOS 10 bugs - suggesions?

### ISSUE THREAD

**Issue by hsakuli** [Mozharovsky/CVCalendar#359]
Ive tried to update my app to iOS 10 using Swift 3, through the XCode 8 beta. I can fix most of the bugs that come with the update, but two specific and seemingly related issues come up: 

1. Cannot convert value of 'Date!' to type 'Date' (aka 'CVDate') in coercion - happens when trying to cast CVDate.date as Date within a function ie. initialLoad(presentedMonthView.date as Date)

2. Cannot convert value of type 'Date' to expected argument type 'Date.type' - happens when appending a Date to a list of Dates: 
var lastWeekDate = calendar.date(from: components)!
var lastWeekDates = [Foundation.Date]
lastWeekDates.append(lastWeekDate)

Any help would be highly appreciated thanks

**Comment by elsesiy** [comment]
Please use the issue template otherwise I'm not able to help you.
