### ISSUE TITLE
There is no way to remove preliminary view

### ISSUE THREAD

**Issue by Antondomashnev** [Mozharovsky/CVCalendar#364]
- [x] I have verified there are no duplicate active or recent bugs, questions, or requests
- [x] I have verified that I am using the latest version of CVCalendar.
- [x] I have given my issue a non-generic title.
## Expected Behavior

This is a hack way to implement something similar to multiple day selections. Below is simplified code.  
If I add the preliminary view using

```
func preliminaryView(shouldDisplayOnDayView dayView: DayView) -> Bool {
  return dayView.date >= beginDate && dayView.date <= endDate
}
```

And then if I refresh the month

```
calendarView.contentController.refreshPresentedMonth()
```

I'll see the expected behavior - multiple day views between `beginDate` and `endDate` are selected. When I select another date - `refreshPresentedMonth` should update UI.
## Current Behavior

The bug appears when I select another date, earlier than `endDate`. After refreshing the presented month I can see still preliminary view that were added by the previous step.
## Possible Solution

In `CVCalendarDayView` store `preliminaryView` and update function:

```
public func preliminarySetup() {
        if let delegate = calendarView.delegate,
            let shouldShow = delegate.preliminaryView?(shouldDisplayOnDayView: self) , shouldShow {
                if let preView = delegate.preliminaryView?(viewOnDayView: self) {
                    preliminaryView = preView
                    insertSubview(preView, at: 0)
                    preView.layer.zPosition = CGFloat(-MAXFLOAT)
                }
        }
        else {
            preliminaryView.removeFromSuperview()
       }
}
```
## Steps to Reproduce (for bugs)

I'll provide a sample project soon.
## Context

I'm trying to mimic the functionality to select multiple dates. This issue prevents me to finish with the possible workaround.
## Your Environment

- Version used (Cocoapods spec): 1.1.0.rc.2
- Device used i.e. iPhone 6S: iPad Air 2 (9.3) Simulator
- Physical device (y/n): no
- Link to your project (if available): private =(

**Comment by elsesiy** [comment]
Closed since I merged your PR, thanks!
