### ISSUE TITLE
Using CVCalendar with Swift 2.2

### ISSUE THREAD

**Issue by zoufishanmehdi** [Mozharovsky/CVCalendar#366]
I'm currently using Swift 2.2 in my project. How can I integrate CVCalendar in my project for the time being? I will eventually upgrade my codebase to Swift 3, but I would like to add this to a feature I'm building now. Thanks

**Comment by hulikp** [comment]
same for me but for swift 2.3

**Comment by elsesiy** [comment]
@zoufishanmehdi You can specify a specific version to use via cocoapods.
@hulikp No support for 2.3 as of today and not planned either.

**Comment by elsesiy** [comment]
Closed due to inactivity.
