### ISSUE TITLE
Selected date gone after swiping two months forwards  and back.

### ISSUE THREAD

**Issue by yaronlevi** [Mozharovsky/CVCalendar#37]
Hi (-:
I am using the the sample project. 

1. Select a date (date is circled with blue background)
2. Swipe to next month.
3. Swipe again to the next month.
4. Swipe back (twice) to the original month. 
5. The blue circle from the selected date is gone.

I would expect the selected date to persist when I swipe away to different months.
Is it expected behaviour? am I missing something here?

(The controller is great! We are about to ship a product with it, can this issue be addressed ?)

**Comment by Mozharovsky** [comment]
Hello @yaronlevi, 

CVCalendar doesn't cache selected days at the moment. If you think this would be a useful enhancement I'll include it in the upcoming release. 

Thank you for your suggestion!
