### ISSUE TITLE
TimeZone-Free selected date??

### ISSUE THREAD

**Issue by muratyasarr** [Mozharovsky/CVCalendar#372]
On two separate physical devices, I set one of the device's timeZone to a different timeZone, keeping other at auto time zone, the framework returns different timeStampts when the same date selected. I select 29th of the October on both of them and print the returning date's _timeStamp_, I see they are different points of time. How to make CVCalendar work with one absolute timeZone and stay consistent across devices? We have an appointment app and all devices _need_ to be consistent. We want every device to see and manage Turkish time zone. How to achieve this?

**Comment by elsesiy** [comment]
Fixed in #385
