### ISSUE TITLE
Implement date range selection

### ISSUE THREAD

**Issue by ssoper** [Mozharovsky/CVCalendar#374]
- [x] I have verified there are no duplicate active or recent bugs, questions, or requests
- [x] I have verified that I am using the latest version of CVCalendar.
- [x] I have given my issue a non-generic title.
## Expected Behavior
1. Select a start date
2. Immediately a configurable number of days is shown to select from
3. Restrict selection to configurable number of days
## Current Behavior

Capability does not currently exist
## Possible Solution

~~https://github.com/Mozharovsky/CVCalendar/pull/373~~
https://github.com/Mozharovsky/CVCalendar/pull/375
## Context

We need to provide users a clear selection of days from which to choose and we want them to be able to choose those dates on a single screen.
## Your Environment

Swift 3.0, iOS 9+, Xcode 8+

**Comment by justdan0227** [comment]
Will this allow us to highlight the selected date range?

**Comment by ssoper** [comment]
Hmm I don’t believe our PR supports that but it should. We’ll continue adding to the code, thanks.

**Comment by justdan0227** [comment]
yeah I implemented it with my local copy via callbacks.  I'll clean it up a bit and let you have a look
