### ISSUE TITLE
Set Gregorian Calendar event thought user choose Buddhist...

### ISSUE THREAD

**Issue by vndn-developers** [Mozharovsky/CVCalendar#377]
I want to set Gregorian Calendar even though user choose their own calendar in Setting (Japanese, Buddhist, Hindu....). Please help me.
Thank you very much.

**Comment by AhmedAlotibi01** [comment]
hijri calender

‏في الاثنين، ٧ نوفمبر، ٢٠١٦, vndn-developers <notifications@github.com> كتب:

**Comment by elsesiy** [comment]
Fixed in #385
