### ISSUE TITLE
Can not view MonthView mode

### ISSUE THREAD

**Issue by TechGuyVN** [Mozharovsky/CVCalendar#38]
Hi,

Thanks for beautiful calendar view.
I setup Default project download and run in simulator iphone 5

I setup in info.plist file MonthView
But i have a problem, i can't view the mode .MonthView. the layout show not correct , maybe wrong size, i adjust by code but not get any luck!.

**Comment by Mozharovsky** [comment]
Hello @TechGuyVN, 

The [pre-release version](https://github.com/Mozharovsky/CVCalendar/releases/tag/1.1.0) is a huge one so I suggest to update your current code. To support the MonthView mode all you have to do is to implement CVCalendarViewDelegate with 2 methods `presentationMode()` and `firstWeekday()`. 

Regards, 
Eugene
