### ISSUE TITLE
Unable to use CVCalendar in asynchronous unit tests 

### ISSUE THREAD

**Issue by Antondomashnev** [Mozharovsky/CVCalendar#380]
- [x] I have verified there are no duplicate active or recent bugs, questions, or requests
- [x] I have verified that I am using the latest version of CVCalendar.
- [x] I have given my issue a non-generic title.

## Expected Behavior
When have a CVCalendar instance in some unit tests for example snapshot tests of `UIViewController` or `UIView`, I should be able to have other tests as asynchronous.

## Current Behavior
Currently, the app is crashing with `bad access` in CVCalendar's related class.

## Possible Solution
Because of animations under the CVCalendar implementations and at the same time `unowned` properties, the lifetime of the subject instance in tests with the CVCalendar dependency can not be less than animation duration.
Current workaround I'm using is to have a static array of subjects to tests which are in memory for the whole testing time. However, this solution doesn't look good to me. Maybe we can think about moving the attributes from `unowned -> weak` and this should potentially fix the `bad access` issue. Or another solution is being able to disable all animations, which sounds weird to me.
@Mozharovsky @elsesiy  any thoughts?

## Context
The issue arrived in the unit testing context with snapshot tests of `UIView` with `CVCalendar` and on the other hands with asynchronous unit tests of other components.

## Your Environment
* Version used (Cocoapods spec): 1.4.0 
* Device used i.e. iPhone 6S: iPad Air 2 simulator 9.3
* Physical device (y/n): n
* Link to your project (if available): private 😞 

I could prepare maybe the test project for showing purpose, but I hope the description was clear 👍

**Comment by elsesiy** [comment]
Hi @Antondomashnev, thanks for pointing out this issue. I haven't checked it myself, but it seems reasonable that the animations cannot occur asynchronously with the current setup. Have you tried declaring `weak` properties instead? The other option seems to be a little more effort (providing a switch to toggle animation)...Feel free to submit a PR if you found a proper solution.

**Comment by Antondomashnev** [comment]
Hey @elsesiy, haven't checked the `weak` yet. Will do this soon and let you know if that works or not. I don't actually think that a switch to toggle animation would be useful for anyone apart from this unit test case. Do you?

**Comment by elsesiy** [comment]
@Antondomashnev Alright, thank you. No I'm with you on that one, the switch may not be very useful except for the described use case.

**Comment by Antondomashnev** [comment]
@elsesiy I've opened the PR, seems like `[weak self]` in completion callbacks done the job 😄

**Comment by elsesiy** [comment]
@Antondomashnev Looks good, I think this one can be closed now. 👍
