### ISSUE TITLE
appearance?.dayLabelWeekdayOutTextColor : myColor[dotIndex] - fatal error: Index out of range

### ISSUE THREAD

**Issue by anatoliykant** [Mozharovsky/CVCalendar#383]
- [x] I have verified there are no duplicate active or recent bugs, questions, or requests
- [x] I have verified that I am using the latest version of CVCalendar.
- [x] I have given my issue a non-generic title.

## Steps to Reproduce (for bugs)

1. I run CVCCalendar Demo on Xcode 8
2. Then I pressed date with three dotMarker (sometimes two dotMarker and two action)
3. Then I swipe next month
4. And I get this Fatal error

## Your Environment

* Version used (Cocoapods spec): 
* Device used i.e. iPhone 6S:
* Physical device (y/n): n
* Link to your project (if available):

**Comment by elsesiy** [comment]
Fixed in #384
