### ISSUE TITLE
CVCalendarViewAppearance.swift

### ISSUE THREAD

**Issue by vitako211** [Mozharovsky/CVCalendar#388]
- [x] I have verified there are no duplicate active or recent bugs, questions, or requests
- [x] I have verified that I am using the latest version of CVCalendar.
- [x] I have given my issue a non-generic title.

Actually I am studying the CVCalendar and when I look into CVCalendarViewAppearance.swift. It seems there is a better way to do the same thing without creating infix operator ~>. This is not a bug I guess this might make the code read better. I am new to swift please advise if I am wrong.

## Current Behavior

CVCalendarViewAppearance.swift

public func setupAppearance() {
spaceBetweenWeekViews ~> delegate.spaceBetweenWeekViews?()
...
}

## Possible Solution

public func setupAppearance() {
spaceBetweenWeekViews = delegate.spaceBetweenWeekViews?() ?? spaceBetweenWeekViews
...
}

Then there is no need for the code:
infix operator ~>
@discardableResult
public func ~> <T: Any>(lhs: inout T?, rhs: T?) -> T? {
    if lhs != nil && rhs != nil {
        lhs = rhs
    }
    return lhs
}

**Comment by elsesiy** [comment]
In general you're right, there's no need to use infix here. The reason we still do is that we're assigning delegate results very often which makes it a cumbersome task if one would always use the elvis operator. I hope that clarifies your question, I'm closing this issue now. Please let me know if you have further remarks.
