### ISSUE TITLE
Scrolling into the past

### ISSUE THREAD

**Issue by rosothefox** [Mozharovsky/CVCalendar#39]
Hey buddy,

Thanks for the awesome calendar. I'm modifying it a bit to match my needs, can you tell me what would be easiest way to disable scrolling into a monthview where all the dayviews (except for isout maybe) are in the past? For example, if today is April. I want to be able to only scroll forward from April and not backwards.

Thanks!

**Comment by Mozharovsky** [comment]
Hello @rosothefox, 

The [new version](https://github.com/Mozharovsky/CVCalendar/releases/tag/1.1.0) will implement the feature you want. Keep watching! 

Regards, 
Eugene
