### ISSUE TITLE
How Can I scroll previous and following calendar view using custom button tap in swift?

### ISSUE THREAD

**Issue by nvnsn386** [Mozharovsky/CVCalendar#394]
![simulator screen shot 02-dec-2016 4 22 59 pm](https://cloud.githubusercontent.com/assets/8234036/20831548/780e425e-b8ab-11e6-9408-c4c55ee12dc4.png)

I want calendar view should scroll on left and right arrow tapping.

**Comment by elsesiy** [comment]
Please use issue template if you need help.
