### ISSUE TITLE
Month with 6 Rows Not always showing 6th row.

### ISSUE THREAD

**Issue by DannyJi** [Mozharovsky/CVCalendar#395]
Sometimes month's with 6 rows do not show the sixth row.  In my app, October 2016, is not showing the 30th and 31st in portrait mode when I navigate to that month.  This happens when I am in portrait mode.  See image.

![img_3852](https://cloud.githubusercontent.com/assets/5400889/20890511/25fa2c04-bad5-11e6-9594-736226fbd3a9.PNG)

When I rotate the device to landscape, the 30th and 31st (of Oct 2016) show.  See image below

![img_3853](https://cloud.githubusercontent.com/assets/5400889/20890534/3e1d2fde-bad5-11e6-879f-fe0330685662.PNG)

If I rotate back to portrait, all looks good.  Even navigating back and forth to other months show the last (6th) row.  It's like the rotation solves a layout issue for the life of that controller.

Interesting:  When we were testing this a few days ago (Nov 2016), this was not happening.  Nov 2016 was the starting calendar, we went back one month to Oct. and it was fine.  Now that is December 2016, Dec 2016 is the starting calendar and I see this effect when I go back two calendar screens.

**Comment by elsesiy** [comment]
@DannyJi Please use the issue template. Provide all information necessary otherwise no help can be provided.
