### ISSUE TITLE
Month with 6 rows not always showing days in the 6th row

### ISSUE THREAD

**Issue by DannyJi** [Mozharovsky/CVCalendar#396]
- [ x ] I have verified there are no duplicate active or recent bugs, questions, or requests
- [ x ] I have verified that I am using the latest version of CVCalendar.
- [ x ] I have given my issue a non-generic title.

## Expected Behavior
Navigating to month with 6 rows should display the 6th row regardless of orientation

## Current Behavior
When using a calendar and navigating to October 2016 from current month of December 2016, the 6th row containing 30th and 31st are not visible when in portrait orientation.  When I rotate device, the two dates on the 6th row appear.  Rotating back to portrait now shows dates in the 6th row as expected.

## Steps to Reproduce (for bugs)
1.  Open my page which is current showing the a monthly calendar for December 2016
2.  Use the back button to navigate two months prior to October 2016
3.  Observe that the two dates in the sixth row are missing (when in portrait)

![img_3852](https://cloud.githubusercontent.com/assets/5400889/20890511/25fa2c04-bad5-11e6-9594-736226fbd3a9.PNG)

4.  Rotate the device to landscape
5. Observe now the two dates (30-Oct-2016 and 31-Oct-2016) appear

![img_3853](https://cloud.githubusercontent.com/assets/5400889/20890534/3e1d2fde-bad5-11e6-879f-fe0330685662.PNG)

6. Rotate back to portrait and observe the dates are still shown as expected.

## Context
This issue is causing our app to fail review since users are not able to see dates in months that have 6 rows unless they rotate the device.

Note:  When we were testing this a few days ago (Nov 2016), this was not happening.  Nov 2016 was the starting calendar, we went back one month to Oct. and it was fine.  Now that is December 2016, Dec 2016 is the starting calendar and I see this effect when I go back two calendar screens.

## Your Environment
Using simulator and iPhone 6Plus

**Comment by elsesiy** [comment]
@DannyJi I see, thanks for reporting the issue. I'll see if I find the time to take a look into it this weekend, but don't expect any immediate solution.

**Comment by DannyJi** [comment]
FYI, out QA team here detected the issue.  

I did find that this is only manifested on iPhone "Plus" models.  Using the simulator - iPhone 6 would be normal, but iPhone 6Plus show this behavior.  Same with iPhone 6s and iPhone 6 Plus.

iPads always seem to work.

**Comment by justinctlam** [comment]
@DannyJi I can't seem to repro this on the demo. Can you try the latest master and see if it occurs in the demo project?

**Comment by DannyJi** [comment]
I tried the latest master and was not able to replicate in the demo.  However, my project's layout is different than the demo.  I have the Calendar View and Menu View in a UIStackView, with other controls.  I am working on making a reduction to illustrate this.  Would that be of interest?

**Comment by elsesiy** [comment]
@DannyJi Ok, I'm going to close this issue then. Sure, it'd be great to have another Demo leveraging UIStackView 👍

**Comment by DannyJi** [comment]
@elsesiy 
Yes.  I was working on this yesterday afternoon after helping figure out that other bug with the supplementaryView.

It does seem like if you have a height constraint on the CalendarView inside a UIStackView, that it does not render months with 6 rows correctly.  I have been working on a reduction - and a potential solution of removing and re-adding my height constraint on ViewDidLoad.  It's simple, but not 100% complete.  It also throws some auto layout constraint issues where it breaks a height = 0 constraint.

I will share when I get further along on this.
