### ISSUE TITLE
Distance between monthLabel and weekday symbols

### ISSUE THREAD

**Issue by probugtivity** [Mozharovsky/CVCalendar#397]
Hi, how do i change the distance between the month label and the weekday symbols? 
![screen shot 2016-12-05 at 9 33 57 pm](https://cloud.githubusercontent.com/assets/20504700/20913207/1a5ee282-bb33-11e6-95f7-7b42f36db007.png)

**Comment by elsesiy** [comment]
@probugtivity Use the issue template please.
