### ISSUE TITLE
How do I add events to the calendar?

### ISSUE THREAD

**Issue by worchyld** [Mozharovsky/CVCalendar#401]
I read the front page documentation, the source code and tried the example.

I would like to add an array of dates to the calendar, but 

I am unclear how to add a singular event to the calendar.  
I am unclear how to add an array of events to the calendar.

Is there not a call for "addEvent" or "addDateToCalendar" ?

**Comment by CarterMiller** [comment]
You need to use `func supplementaryView(shouldDisplayOnDayView dayView: DayView) -> Bool` 

Within that function you either return true or false if you want the supplementary indicator drawn - a blue circle by default, but you can do whatever you want.  You will need to hold your even information somewhere else, and interrogate it based on the dayView value.

It took me a LONG time to find that if you are making these changes dynamically, you will need to call 
`calendarView.contentController.refreshPresentedMonth()` 
before you see the changes, as this method appears to assume that it will set up the supplementary view once at initialisation, and you need to force the refresh

**Comment by elsesiy** [comment]
@CarterMiller is right, if you need further help please open a new issue.
