### ISSUE TITLE
Month View Frame change 

### ISSUE THREAD

**Issue by arpandesai** [Mozharovsky/CVCalendar#402]
I have changed dotmarker's Y position in cv calendar . While showing it, it gets cut off at last Row . How can i change MonthView's frame ?
![cutdot](https://cloud.githubusercontent.com/assets/507842/21138099/9a43ae0e-c152-11e6-9926-2586cd0b854b.png)

**Comment by elsesiy** [comment]
Please use the issue template if you need help.
