### ISSUE TITLE
CVCalendar 1.4.1 not in Cocoapods old repository

### ISSUE THREAD

**Issue by sultankme** [Mozharovsky/CVCalendar#405]
Hello,

I'm still using Cocoapods 0.39 because of some issues in Cocoapods 1.1.1, so instead of using 'https://github.com/CocoaPods/Specs.git' I'm using 'https://github.com/CocoaPods/Old-Specs.git'.

Can you upload CVCalendar version 1.4.1 there? I only found CVCalendar version 1.4.0.

Thanks

**Comment by elsesiy** [comment]
@sultankme I haven't found a possibility to dedicate a push to a certain trunk. I guess that cocoapods is mirroring the specs once in a while and haven't done it yet for your desired spec. Unfortunately there's nothing I can do, but I strongly suggest you switch to the current version if you can.
