### ISSUE TITLE
How do i Jump to next  or previous Year?

### ISSUE THREAD

**Issue by moosa0709** [Mozharovsky/CVCalendar#410]
I am using CVCalender but worried about how can i change year like we change Month by next and previous button?

**Comment by elsesiy** [comment]
Please use the issue template.

**Comment by moosa0709** [comment]
Please use the issue template. this is not an answer

**Comment by elsesiy** [comment]
@moosa0709 It is as you need help and need to provide all relevant information for us to help you.

**Comment by kutakmir** [comment]
https://github.com/CVCalendar/CVCalendar/issues/431

:)
