### ISSUE TITLE
How to enable selection for current day

### ISSUE THREAD

**Issue by rjjohnpatrickcruz** [Mozharovsky/CVCalendar#413]
Hi everyone,

Can anyone help me to enable the selection of the current day? what api or delegate should I use for this.

Thank you in advance!

**Comment by CarterMiller** [comment]
Do you mean display the current day?  That's what you should get by default.

If you mean that you want to show the current month, and click on today, you could use this
`calendarView.toggleViewWithDate(Date())`

You may also need to call 
`calendarView.presentedDate = CVDate(date:Date(), calendar: currentCalendar!)`
if you have a month label to update, as in the examples

**Comment by rjjohnpatrickcruz** [comment]
Hi @CarterMiller ,

Thanks for your help! I can now select also the current date.

Cheers!
