### ISSUE TITLE
Question: Is there a way to change between month view and week view if the device is rotated

### ISSUE THREAD

**Issue by RyanHop3** [Mozharovsky/CVCalendar#415]
Hi, this may of been asked before but I cant seem to find the answer.
 I am wondering if it is possible for CVCalendar to display the normal monthView when the device is in portrait orientation and change to weekView when the device is rotated to landscape view to fit within the smaller screen space.

Thanks, Ryan.

**Comment by elsesiy** [comment]
There is no built-in functionality but you can easily implement such a feature by yourself. Just handle the rotation within viewWillTransition (UIViewController) and set the calendar layout respectively.

**Comment by RyanHop3** [comment]
I have tried to use viewWillTransition to set the calendar layout using the following code:

`override func viewWillTransition(to size: CGSize, with coordinator: UIViewControllerTransitionCoordinator) {
        super.viewWillTransition(to: size, with: coordinator)
       
          self.presentationMode()
        }`

`func presentationMode() -> CalendarMode {
        
        let isPhone: Bool = UIDevice.current.userInterfaceIdiom == .phone
        let isLandscape: Bool = UIDevice.current.orientation.isLandscape
            
        if isPhone == true && isLandscape == true {
            return.weekView
        } else {
                return .monthView
        }
    }`

But the calendar is remaining in monthView when rotated in an IPhone.

Thanks, Ryan.
