### ISSUE TITLE
How do I set start and end date range in the Calendar? 

### ISSUE THREAD

**Issue by Srikanth-Codebees** [Mozharovsky/CVCalendar#416]
- [ ] I have verified there are no duplicate active or recent bugs, questions, or requests
- [ ] I have verified that I am using the latest version of CVCalendar.
- [ ] I have given my issue a non-generic title.

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used (Cocoapods spec):
* Device used i.e. iPhone 6S:
* Physical device (y/n):
* Link to your project (if available):

**Comment by elsesiy** [comment]
Please fill in the issue template.

**Comment by RyanHop3** [comment]
I tried the following code but the calendar is staying in monthView when rotated. Any suggestions?


`   override func viewWillTransition(to size: CGSize, with coordinator: UIViewControllerTransitionCoordinator) {
        super.viewWillTransition(to: size, with: coordinator)

        let isPhone: Bool = UIDevice.current.userInterfaceIdiom == .phone
        let isLandscape: Bool = UIDevice.current.orientation.isLandscape
        
        if isPhone && isLandscape {
            coordinator.animate(alongsideTransition: nil, completion: { _ in
                self.presentationMode()
            })
            }
        else {return}
        }
    
 

extension workoutLogViewController {
    
    /// Required method to implement!
    func presentationMode() -> CalendarMode {
        
        let isPhone: Bool = UIDevice.current.userInterfaceIdiom == .phone
        let isLandscape: Bool = UIDevice.current.orientation.isLandscape
            
        if isPhone == true && isLandscape == true {
            return.weekView
        } else {
                return .monthView
        }
    }
}`
