### ISSUE TITLE
Select dayOut and change month

### ISSUE THREAD

**Issue by schulz89sp** [Mozharovsky/CVCalendar#418]
If I select the month of January for example, 3 February, the month is changed and the console is printed "on February 3 is selected," but then immediately switches to the "February 1 is selected", why?
If I change the month by scrolling on the screen is right it is placed the blue on the first of the month, but if I know pick from the month before, then if I press on the 3, blue must be the month after the 3? I'm wrong?

**Comment by elsesiy** [comment]
Use the issue template.
