### ISSUE TITLE
Xode 6.3 beta using Swift v1.2

### ISSUE THREAD

**Issue by martjemeyer** [Mozharovsky/CVCalendar#42]
Hey, today I tried to run my project in Xcode 6.3, with Swift 1.2, and it gave me a lot of Warnings (deprecated stuffs) and errors, which are easily fixed in my case. And I think the code turned out to be better because of that. 
But also your calendar gives errors here and there. Mostly where you initialize your classes. So maybe it might not be bad to try to beta before you release your calendar and see if you can optimize your code before that. So when they force the new Xcode your calendar will still work.
![screenshot 2015-04-08 11 31 28](https://cloud.githubusercontent.com/assets/9798987/7042665/c2fefae6-dde3-11e4-9f63-4e111ad2b3e3.png)

I'm not sure how to fix those my self, so until then I revert back to the last non beta version of Xcode:)

**Comment by martjemeyer** [comment]
I changed all warning and errors Swift v1.2 was suggesting, but it is not backwards compatible. So maybe create two versions? Since I don't know how long we will be able to use the "older" swift.

**Comment by thajcak** [comment]
Can you post those changes? I'm having issues myself.

**Comment by wgsomerville** [comment]
I forked the repo and implemented some changes to make the library work with swift 1.2 [here](https://github.com/wgsomerville/CVCalendar/tree/swift1.2).  These will likely only be temporary fixes, but it should work until an official update is released.

**Comment by FrancisBaileyH** [comment]
@wgsomerville, looks like you beat me to it, however I noticed we're both still getting deprecation warnings for the CalendarUnits. Anyone have a fix for that yet?

**Comment by thajcak** [comment]
@wgsomerville @FrancisBaileyH Moving the unit itself to the end. .MonthCalendarUnit becomes .CalendarUnitMonth. Week is the only strange one in that it becomes .CalendarUnitWeekOfYear.

**Comment by wgsomerville** [comment]
Huh, I thought I had fixed that, let me look at it.  What I had found was that you had to change 

``` swift 
NSCalendarUnit.DayCalendarUnit
```
to 
``` swift
NSCalendarUnit.CalendarUnitDay
```
for week you have to use week of month or year instead of just week.

**Comment by wgsomerville** [comment]
@thajcak did you notice any difference between .CalendarUnitWeekOfYear and .CalendarUnitWeekOfMonth?

**Comment by thajcak** [comment]
@wgsomerville Week of Month goes to 4 and resets each month, Week of Year goes to 52/53 and resets each year. 

.WeekCalendarUnit maps to the .CalendarUnitWeekOfYear according to the deprecation note so that's what I switched these to.

**Comment by wgsomerville** [comment]
Ah good call, I'll update my changes.

**Comment by FrancisBaileyH** [comment]
@thajcak @wgsomerville, great thanks for the insight!

**Comment by wgsomerville** [comment]
Just an FYI for anyone who uses the changes I made:  because of a naming conflict with an Obj-c selector, I had to change the description() function in CVDate to dateDescription().  Just be aware of that if you use it in your code.

**Comment by Mozharovsky** [comment]
Hello @martjemeyer, @thajcak, @wgsomerville, 

Thank you so much in contributing to this issue. I haven't been looking for Swift 1.2 Beta but today it's been finally released with Xcode 6.3. Some changes came so somewhere the code isn't updated to the current language syntax. 

I've just pushed the changes to develop branch. Check this commit 8369c659dc0780a6052d44dfa1beb1838086f0ee. Note that develop branch is basically active one so more commits to come. 

As for your discussion on NSCalendarUnit constants then Apple engineers simply rejected using outdated Objective-C like naming rules such as NSCalendarUnit.MonthCalendarUnit instead they use NSCalendarUnit.CalendarUnitMonth which is ultimately the same but more Swifty. I guess they started working on migrating NSCalendar foundation stuff into native Swift one. 

Major updates this weekend comes! Keep watching. 

Regards, 
Eugene

**Comment by martjemeyer** [comment]
I see! I was not aware on accessing the dev branch :)
Thank you for your hard work!

**Comment by dmelgar** [comment]
How should CVCalendar be installed in an Xcode 6.3.x project? 
Even if I use the commit mentioned above, CVCalendar/CVCalendar/CVCalendarMenuView.swift overrides init() and generates an error.
However, 'CVCalendar Demo'/CVCalendar/CVCalendarMenuView.swift includes the changes to make it work in Swift 1.2.

Whats the intended difference between CVCalendar and CVCalendar Demo.
