### ISSUE TITLE
Spelling error

### ISSUE THREAD

**Issue by mengelhart** [Mozharovsky/CVCalendar#43]
You spelled "Architecture" wrong in the README.. currently it says "Arcitecture".

**Comment by mengelhart** [comment]
I opened a pull request for you if you want to merge

https://github.com/Mozharovsky/CVCalendar/pull/44

Cheers
Mike

**Comment by Mozharovsky** [comment]
Hello @mengelhart, 

Thank you for fixing this issue. I'll merge the pull request with releasing a new CVCalendar version. 

Regards, 
Eugene
