### ISSUE TITLE
CVCalendarView doesn't load on when Simulated Metric == iPhone 4-inch

### ISSUE THREAD

**Issue by gjones** [Mozharovsky/CVCalendar#46]
Hi there, 
It seems when you have your view controller set to iPhone 4-inch in the storyboard, the calendarView doesn't load on devices older/smaller than the iPhone 6. Not sure why this is but you can test it in your new demo. 

Steps to reproduce: 
- Open most recent version of demo in Xcode 
- Go to storyboard and select the viewController
- Under attributes inspect, set size to iPhone 4-inch
- Build and run on iPhone 5S.

Thought I'd save others a bunch of time by reporting it here.

**Comment by gjones** [comment]
Just to add to this, it looks as though the CVCalendarView fails to load whenever the simulated size matches the device size. For example setting the simulated size to iPhone 4.7-inch means it no longer loads on the iPhone 6, 5.5-inch doesn't show on the 6 Plus etc.

**Comment by Mozharovsky** [comment]
Hello @gjones,

Thank you for the reported issue. 

You're trying to use CVCalendar without auto layout as a result it doesn't update frames since they aren't changed. I've just pushed the code which should have fixed that issue. Please let me know if it works for you. 

Regards, 
Eugene

**Comment by gjones** [comment]
@Mozharovsky I see there's been lots of changes to the file structure since I reported this so it'll take me a bit of time migrate my app to the newer version and test out these updates. I did try the updated demo and the problem seemed to be fixed so I'm sure it is. 

Thanks for responding so quickly and of course for the excellent CVCalendar.
