### ISSUE TITLE
Current day highlighted text overlay bug. 

### ISSUE THREAD

**Issue by FrancisBaileyH** [Mozharovsky/CVCalendar#48]
The gif below describes it much better than I can, but essentially, when I toggle between tabs the currently highlighted day produces a text overlay bug of sorts. I'm currently searching for a solution, but I'd thought I'd see if you have any quick fixes first. 

![cvcalendarbug](https://cloud.githubusercontent.com/assets/4231049/7213341/22fad2e2-e52f-11e4-84b4-da345dd0fda8.gif)

**Comment by Mozharovsky** [comment]
Hello @FrancisBaileyH, 

This bug is fixed in the pre-release of 1.1.0 version. You can get it [here](https://github.com/Mozharovsky/CVCalendar/releases/tag/1.1.0). Note, that it's under an active maintenance so more changes to come. 

In order to fix your issue simply move frames' update commitment to `viewDidLayoutSubviews()` method. It's fixed in the demo project. Also the actual source code has the following directory: CVCalendar-develop / CVCalendar Demo / CVCalendar.  

Hope it helps. 

P.S. If it works for you let me know so I can close the issue. 

Regards, 
Eugene

**Comment by FrancisBaileyH** [comment]
Hi @Mozharovsky,

Moving the `commitCalendarViewUpdate()` and `commitMenuViewUpdate()` into the `viewDidLayoutSubviews()` method did not work, unfortunately. Instead, the text overlay bug is no permanently visible, no matter what action was taken.

At this point, we're close to ready for our release and don't want to upgrade the library just yet.

Was there any other code you changed that may have fixed the bug on your end?

**Comment by martjemeyer** [comment]
Are you sure you got the CVCalendar folder from the CVCalendar Demo/CVCalendar/ and not the CVCalendar/ from the root? Since there are two CVCalendar folders in the Develop branch. I had the same problems as you, but I can't reproduce it anymore how hard I try.

**Comment by FrancisBaileyH** [comment]
@martjemeyer I haven't actually updated the library, I was just trying out the quick fix that @Mozharovsky had mentioned.

**Comment by FrancisBaileyH** [comment]
Okay, I've implemented the new library in a branch and it does indeed fix the issue. Just curious, before I close this issue, if anyone noticed the menuView doesn't appear. Is there something different I need to do?

**Comment by martjemeyer** [comment]
I Added the following fixed the issue on my side:

// MARK: - CVCalendarMenuViewDelegate

extension yourViewController: CVCalendarMenuViewDelegate {
    // firstWeekday() has been already implemented.
}

I must say I used Eugenes extension way of initializing the calendar in his updated demo. But I think you can add it behind your last closing curly bracket of the class

**Comment by FrancisBaileyH** [comment]
@martjemeyer, thanks, I added implemented the delegate protocol and then found out you have to hook up the menuView delegate from the main storyboard as well.
