### ISSUE TITLE
Current calendar date does not update when date changes. 

### ISSUE THREAD

**Issue by FrancisBaileyH** [Mozharovsky/CVCalendar#51]
I'm not sure if this implementation is supposed to be left up to the user or not, but I noticed that the current date in the calendar does not update when the real date changes. 

I'm assuming that's because the calendar is only committed once during viewDidLoadSubviews. In any event I thought I would point it out, in case it would make for an enhancement, or perhaps it's best left up to the user to implement.

**Comment by Mozharovsky** [comment]
Hello @FrancisBaileyH, 

Thank you for reporting the issue. 

The control coordinator simply does not update calendar view's presented date. It'll be fixed as soon as possible. Keep watching!

Regards, 
Eugene

**Comment by FrancisBaileyH** [comment]
Hi @Mozharovsky I forgot to mention I'm using version 1.10, in case it makes any difference.

Thanks for the awesome calendar by the way. Our application simply wouldn't be the same without it.
