### ISSUE TITLE
Changing Month Label

### ISSUE THREAD

**Issue by manosai** [Mozharovsky/CVCalendar#60]
What's the simplest way to change the month label when a user swipes left or right to change the month view? I see the presentedDateUpdated method but I'm unsure how to actually implement this. Are there any examples I can look at?

**Comment by Mozharovsky** [comment]
Hello @manosai, 

This is what the demo project uses. 

```swift
func presentedDateUpdated(date: CVDate) {
        if monthLabel.text != date.globalDescription && self.animationFinished {
            let updatedMonthLabel = UILabel()
            updatedMonthLabel.textColor = monthLabel.textColor
            updatedMonthLabel.font = monthLabel.font
            updatedMonthLabel.textAlignment = .Center
            updatedMonthLabel.text = date.globalDescription
            updatedMonthLabel.sizeToFit()
            updatedMonthLabel.alpha = 0
            updatedMonthLabel.center = self.monthLabel.center
            
            let offset = CGFloat(48)
            updatedMonthLabel.transform = CGAffineTransformMakeTranslation(0, offset)
            updatedMonthLabel.transform = CGAffineTransformMakeScale(1, 0.1)
            
            UIView.animateWithDuration(0.35, delay: 0, options: UIViewAnimationOptions.CurveEaseIn, animations: {
                self.animationFinished = false
                self.monthLabel.transform = CGAffineTransformMakeTranslation(0, -offset)
                self.monthLabel.transform = CGAffineTransformMakeScale(1, 0.1)
                self.monthLabel.alpha = 0
                
                updatedMonthLabel.alpha = 1
                updatedMonthLabel.transform = CGAffineTransformIdentity
                
                }) { _ in
                    
                    self.animationFinished = true
                    self.monthLabel.frame = updatedMonthLabel.frame
                    self.monthLabel.text = updatedMonthLabel.text
                    self.monthLabel.transform = CGAffineTransformIdentity
                    self.monthLabel.alpha = 1
                    updatedMonthLabel.removeFromSuperview()
            }
            
            self.view.insertSubview(updatedMonthLabel, aboveSubview: self.monthLabel)
        }
    }
```

Note that this is an animated way. If you want to keep it simple you can add your animation or don't use one at all. 

Hope it helps. 

P.S. Please close the issue if it is ok for you otherwise let me know!

Regards, 
Eugene

**Comment by manosai** [comment]
Hi Eugene, 

Thanks for your prompt reply! I saw the method you've pasted in the demo project but I wasn't sure where the method itself gets called. I copy pasted "presentedDateUpdated" into my UIViewController for now but don't see where in the demo that the method gets called on a swipe left/right action.

Thanks!
Manosai

**Comment by Mozharovsky** [comment]
There is an observation method `didSet` on <b>dateLabel</b> in CVCalendarView. 

```swift
    var presentedDate: Date! {
        didSet {
            if let oldValue = oldValue {
                delegate?.presentedDateUpdated?(presentedDate)
            }
        }
    }
```

It's changed every time CVCalendarView handles the touch on a day view. 

```swift
    func didSelectDayView(dayView: CVCalendarDayView) {
        if let controller = contentController {
            presentedDate = dayView.date
            delegate?.didSelectDayView?(dayView)
            controller.performedDayViewSelection(dayView) 
        }
    }
```

That's it. :) 

Regards, 
Eugene

**Comment by manosai** [comment]
Hi Eugene, 

Got it. I think the confusion is because I am using CVCalendar from the master branch and not the develop branch so the two code snippets in your last response are different for the version of your codebase I'm working with. 

I changed the two methods you pointed out and though it compiles, I'm still not seeing the label change when running the simulator: https://github.com/manosai/frii/blob/master/CVCalendar/CVCalendarView.swift

Thanks,
Manosai

**Comment by Mozharovsky** [comment]
Hello @manosai, 

First of all, I recommend to use the latest code pushed to the develop branch. As for your issue, then you shouldn't change anything from CVCalendar source until you want either to fix a bug or bring an enhancement. 

1. Once you've implemented CVCalendarViewDelegate & CVCalendarMenuViewDelegate protocols and their required methods CVCalendar will work fine. 
2. On your controller's view's load you can set the text for your label or whatever. 
3. When you change a month (if you're running a MonthView mode) CVCalendar will notify you about presented date change through the delegate method `presentedDateUpdated(date: Date)`. There you should update your label or anything representing the current date. 

After all your ViewController should look like one below. 

```swift
class ViewController: UIViewController, CVCalendarViewDelegate, CVCalendarMenuViewDelegate {
    @IBOutlet weak var menuView: CVCalendarMenuView!
    @IBOutlet weak var calendarView: CVCalendarView!
    
    override func viewDidLoad() {
        super.viewDidLoad()
        updateTitleText()
    }
    
    override func viewDidLayoutSubviews() {
        super.viewDidLayoutSubviews()
        menuView.commitMenuViewUpdate()
        
        // Once your controller's loaded you can update the label with current date.
        calendarView.commitCalendarViewUpdate()
    }
    
    /**
        Updates the navigation bar's title.
     */
    
    func updateTitleText() {
        navigationController?.navigationBar.topItem?.title = calendarView.presentedDate.globalDescription
    }
    
    // MARK: - CVCalendarViewDelegate
    
    /**
        These two methods are required and you must implement them.
     */
    
    func presentationMode() -> CalendarMode {
        return .MonthView
    }
    
    func firstWeekday() -> Weekday {
        return .Sunday
    }
    
    /**
        This method is an optional. 
        It notifies you each time the current date's been changed.
    */
    
    func presentedDateUpdated(date: Date) {
        updateTitleText()
    }
}
```

**Comment by manosai** [comment]
Hi Eugene,

Sorry for never following up. Unfortunately, I made quite a few changes to the calendar codebase to add some functionality so I'd like to avoid having to start from scratch again. 

I spent some time trying to implement the methods as you've described them but I'm still not able to see the month being changed on swipe. I added some print statements to see if presentedDateUpdated gets called when the swipe action occurs but it does not seem to be the case. If you have any time, would you be able to take a look at what I'm doing wrong? 

CVCalendarView: https://github.com/manosai/frii/blob/master/CVCalendar/CVCalendarView.swift
ViewController: https://github.com/manosai/frii/blob/master/Frii/StartDateViewController.swift

This is the last feature I want to get working in using the CVCalendar for my app and I have to say, it's been super useful and great. I really appreciate the time you've put into open-sourcing this and hope I can resolve this last issue.

**Comment by Tejal16** [comment]
hello Mozharovsky

I am facing one issue in CVCalendar.i had implemented Weekview mode of calendar as my project requirement .i want to  implement next month and previous month on next - Previous button.But i have set weekmode then i can't able to move direct on next month. If i click on next month it's move on next week.please if you have any solution then let me know.i am waiting for your reply :-)

**Comment by Tejal16** [comment]
hello Mozharovsky

I am facing one issue in CVCalendar.i had implemented Weekview mode of calendar as my project requirement .i want to implement next month and previous month on next - Previous button.But i have set weekmode then i can't able to move direct on next month. If i click on next month it's move on next week.please if you have any solution then let me know.i am waiting for your reply :-)

**Comment by derekwinton** [comment]
For anyone coming to this after a move to Swift 3, follow @Mozharovsky 's code above but change the presentedDateUpdated function to :

    func presentedDateUpdated(date: CVDate) {
        updateTitleText()
    }
