### ISSUE TITLE
Not displaying all dates for month

### ISSUE THREAD

**Issue by Trifusion** [Mozharovsky/CVCalendar#65]
When a month requires 6 weeks (May 2015) the initial display only shows 5 weeks and truncates the last week (May 31st). I believe this may have to do with the setup of the adjacent (previous & following) months off screen.

Greg
![ios simulator screen shot may 2 2015 7 10 11 am](https://cloud.githubusercontent.com/assets/693993/7440844/52c9b26a-f09a-11e4-99df-c8f35c2fbdfb.png)

**Comment by Trifusion** [comment]
Scrolling to the next/previous month and then scrolling back fixes display issue, perhaps just the initial display setup has the issue.

![ios simulator screen shot may 2 2015 7 13 33 am](https://cloud.githubusercontent.com/assets/693993/7440854/c65ab7e2-f09a-11e4-9786-1098d211be3f.png)

**Comment by Mozharovsky** [comment]
Hello @Trifusion, 

Thank you for the report! 
The issue was that the scroll view didn't match presented month view's size on initial load. It's fixed now. 

Regards, 
Eugene
