### ISSUE TITLE
Initializer does not override a designated initializer from its superclass

### ISSUE THREAD

**Issue by datomnurdin** [Mozharovsky/CVCalendar#66]
I got this error after updated xcode 6.3.1.

```
/Users/MNurdin/Documents/iOS/xxxxx/Pods/CVCalendar/CVCalendar/CVCalendarView.swift:112:14: Initializer does not override a designated initializer from its superclass
```

This code

```
 override init() {
        super.init() //error here
        
        hidden = true
        loadCalendarMode()
        contentController = CVCalendarContentViewController(calendarView: self, frame: bounds)
    }
```

**Comment by rajavikram** [comment]
+1
Same here, 
Got this issue right after i updated my XCode to 6.3.1 .
The readme says this project supports Swift 1.2 .
So this should not happen right?

**Comment by Mozharovsky** [comment]
Hello @datomnurdin, 

You're using the outdated CVCalendar version from the <b>master</b> branch. The most recent code is pushed to the <b>develop</b> branch. By the way I've updated the README document which says: 

> GLOBAL CHANGES

> The project is currently being under an active maintenance. We're going to bring a lot of new features  as well as fix all bugs and optimize the library to make it incredibly efficient and fast (see the full list). API isn't changed so you don't pay anything for the update. The code can be found in this branch. It supports Swift 1.2.

Note that the code directory is: CVCalendar-develop / CVCalendar Demo / CVCalendar. 

In case of any issues or questions leave a comment here. 

Regards, 
Eugene
