### ISSUE TITLE
How to install CVCalendar 1.1.0 from cocoapods ?

### ISSUE THREAD

**Issue by rajavikram** [Mozharovsky/CVCalendar#67]
Hi Eugene,
Thanks for this great swift calendar.
Recently i updated my Xcode to 6.3.1
Then some errors popped up in CVCalendar .
Read the issues and your response to use pre-release 1.1.0

When i try to instal it on pods i get the following error:

[!] Unable to satisfy the following requirements:

- `CVCalendar (= 1.1.0)` required by `Podfile`

**Comment by Mozharovsky** [comment]
Hello @rajavikram, 

Thank you for using this software. 

CVCalendar is currently being under an active maintenance. Which means that the release version isn't ready yet. The temporary solution for now is to simply drag-n-drop the code into your project. The final changes will come in a week or two with the stable release version. 

Keep watching!

Regards, 
Eugene

**Comment by skywinder** [comment]
:+1: for cocoapods version! Still waiting!

**Comment by Mozharovsky** [comment]
Hello @skywinder, 

Updates are coming. Please wait a little bit more. :) 

Regards, 
Eugene

**Comment by dwightwatson** [comment]
Thanks for the work on this! Are you able to provide a rough estimate for when we will see the stable release?

**Comment by AnthonyMDev** [comment]
+1 for new version on Cocoapods. Any idea when this will be ready? Thanks!

**Comment by Mozharovsky** [comment]
Resolved #111
