### ISSUE TITLE
Not compiling with xcode 6.3.1 Swift1.2 

### ISSUE THREAD

**Issue by prabhatk** [Mozharovsky/CVCalendar#68]
Please have a look for the new Xcode and swift1.2 version

**Comment by Mozharovsky** [comment]
Hello @prabhatk, 

CVCalendar does support Swift 1.2. You have to use the code from the [develop](https://github.com/Mozharovsky/CVCalendar/tree/develop) branch. 

Note that there were some changes so you must implement two protocols (CVCalendarViewDelegate, CVCalendarMenuViewDelegate). 

Regards, 
Eugene
