### ISSUE TITLE
Using Library with ObjC?

### ISSUE THREAD

**Issue by bchessin** [Mozharovsky/CVCalendar#70]
Hi,

Is there any documentation on how to use this library with a strictly Objective-C project? I am trying to get into using Swift and this library as it is very comprehensive but any guidelines on how to do this would be appreciated!

-Brad

**Comment by Mozharovsky** [comment]
Hello @Objective-Zero, 

I'll pay my attention to this issue in the following few days and let you know here. 

Regards, 
Eugene

**Comment by Objective-Zero** [comment]
Any updates?

**Comment by Mozharovsky** [comment]
Hello @Objective-Zero, 

Apple has provided all the necessary information on using Swift & Objective-C code in the same project [in this article](https://developer.apple.com/library/prerelease/ios/documentation/Swift/Conceptual/BuildingCocoaApps/MixandMatch.html). Anyway, it says that all identifiers must be public for Swift code. [b]CVCalendar[/b] is not yet marked but it will be in a couple of days. 

Hope it helps. 

Regards, 
Eugene

**Comment by Mozharovsky** [comment]
Hey @Objective-Zero, 

Did you figure out the integration process? 

Regards, 
Eugene

**Comment by Objective-Zero** [comment]
@Mozharovsky No unfortunately not, I am sticking with Objective C in my app and without documentation it is proving difficult to integrate Swift libraries.

**Comment by Mozharovsky** [comment]
Hey @Objective-Zero, 

I hope you're doing well. Try out [this tutorial](http://www.appentwicklungberlin.de/integrating-objective-c-with-swift/). And make sure you're using the most recent CVCalendar version.

**Comment by vichiodo** [comment]
Hi, do you have any documentation of how to mark dots on specific dates in the CVCalendar?
