### ISSUE TITLE
Latest version not working without autolayout?

### ISSUE THREAD

**Issue by s6joui** [Mozharovsky/CVCalendar#72]
I've updated my app to the newest version in the develop branch and the calendar is not displayed. I can only see a small dot on the top left part of the view.

I've tried the demo app and it works but if you disable autolayout you get the same problem I'm seeing in my app.

Is it not possible to display the calendar without autolayout? I could use it with the previous version.

Thank you very much

**Comment by Mozharovsky** [comment]
Hello @s6joui, 

Thank you for the report! 

CVCalendar's been updated to support dynamic size and initially it was built on AutoLayout. From now it works without AutoLayout as well. Though I don't completely understand what's the point of going this way... 

Please close the issue if it works for you. 

Regards, 
Eugene

**Comment by s6joui** [comment]
It works! Thank you! :D
