### ISSUE TITLE
Core Code for Calendar is under Demo in Develop Branch

### ISSUE THREAD

**Issue by thomasbaldwin** [Mozharovsky/CVCalendar#74]
The code in CVCalendar/CVCalendar Demo/CVCalendar appears to be the more updated code than the code in CVCalendar/CVCalendar/ in the Develop branch

**Comment by Trifusion** [comment]
The changes I sent a pull request for were only in demo.

Greg

**Comment by thomasbaldwinj** [comment]
Should we update CVCalendar/CVCalendar to match CVCalendar/CVCalendar Demo/CVCalendar for organization purposes?
