### ISSUE TITLE
Make calendar resize without using a height constraint

### ISSUE THREAD

**Issue by thomasbaldwinj** [Mozharovsky/CVCalendar#76]
Hey, first off let me start by saying this calendar is great. Currently, I'm trying to use it to create a calendar similar to this:  https://dribbble.com/shots/1878977-Calendar-Revision-For-iOS-App/attachments/318416

In order to accomplish this, I'm using a TableView for the entire page, and I'm putting your calendar in a tableview cell, which forces me to use the following constraints so the height of the tableview cell will be dynamic and adjust based off the calendar's height:

``
calendarView.autoPinEdgeToSuperviewEdge(.Top, withInset: 0)
calendarView.autoPinEdgeToSuperviewEdge(.Leading, withInset: 0)
calendarView.autoPinEdgeToSuperviewEdge(.Trailing, withInset: 0)
calendarView.autoPinEdgeToSuperviewEdge(.Bottom, withInset: 0)
``

This is what the month of May currently looks like for me: 

![screen shot 2015-05-19 at 8 01 28 pm](https://cloud.githubusercontent.com/assets/5099084/7716565/dbcb247a-fe61-11e4-90fb-18fb9778484f.png)

Notice that there is only 30 days, when the month of may has 31 days, meaning the calendar needs to update in height because it's missing a row.

I noticed your calendar only updates the height if a height constraint is supplied for the calendarView. So I added the height constraint and removed the `calendarView.autoPinEdgeToSuperviewEdge(.Bottom, withInset: 0)` (so I wouldn't have conflicting constraints) to the calendarView to cause it to update it's height when necessary.

![screen shot 2015-05-19 at 8 44 09 pm](https://cloud.githubusercontent.com/assets/5099084/7716996/eb133f0c-fe67-11e4-92d2-cafaf52867f1.png)

As you can see the calendar height is now going over it's table cell. Is there a way we can accomplish the calendar resizing in height for necessary months without using a height constraint? The ideal solution for me would work without a height constraint, and just update the calendar's frame when needed.  (I noticed the calendar will update in height if you're switching between months, but not initial load. Also it seems only the scrollView's frame updates in height, not the calendarView's)

What do you think?

I've posted my code here https://github.com/thomasbaldwinj/Table-View-With-Dynamic-Subview-Height (the version where I'm using the top, leading edge, trailing edge, and bottom constraints, instead of the height constraint) in case you want to take a look.

**Comment by thomasbaldwinj** [comment]
OK I fugred

**Comment by nspassov** [comment]
Hi Thomas, I was wondering if you have found a solution?

**Comment by thomasbaldwin** [comment]
Yeah I ended up figuring it out. The calendar resizes using the height constraint which is perfectly fine. To get it to update the TableViewCell when the height changes, add this code

```swift
extension CVCalendarView {
    override func layoutIfNeeded() {
        super.layoutIfNeeded()
        
        for subview in subviews {
            if let scrollView = subview as? UIScrollView {
                NSNotificationCenter.defaultCenter().postNotificationName(UIContentSizeCategoryDidChangeNotification, object: scrollView)
            }
        }
    }
}
```
