### ISSUE TITLE
Refresh calendar (dotMarkers)

### ISSUE THREAD

**Issue by matlamenace** [Mozharovsky/CVCalendar#78]
Hello,

 First of all, I wanted to congratulate you and thank you for you great CVCalendar !

 I'm currently trying to use your CVCalendar from the 'Develop' branch as I recently upgraded to Xcode 6.3 and Swift 1.2, and I'm struggling to refresh (update / reload) the multiple dotMarkers. I'm using the main view controller from a TabBarController, so the viewDidLoad function is only called once. I've tried many things (func viewDidAppear() / func viewDidLayoutSubviews()) to refresh the dotMarkers accordingly to my data being refreshed. 
For instance, when deleting or adding an event, my TableView will update with the changes made but not the dotMarkers presented on the calendar. To refresh, the calendar I need to restart the application and then it works.

Could you please help me ?

Also, I wanted to know when your CVCalendar will be fully operational for swift 1.2 ?

Many thanks (in advance) !

**Comment by Mozharovsky** [comment]
Hello @matlamenace, 

This feature will be added as soon as possible. Thank you for reporting!

Regards, 
Eugene

**Comment by matlamenace** [comment]
Hello,

It's been 3 months now... I've tried to work it out on myself, but did not succeed... 

When will you add this important feature : ReloadDotMarkers, please ?

Thanking you in advance !

**Comment by linkcrux** [comment]
Hi,

Thanks again for this wondering component, appreciate if this feature can be taken forward. +1

**Comment by jose920405** [comment]
........ nothing?

**Comment by elsesiy** [comment]
@jose920405 We're working on it. Please sit tight, we have a couple of issues to consider atm.

**Comment by pr0gramm3r8hai** [comment]
@Mozharovsky . waiting for it, ... And please make it on swift 1.2 also ,

**Comment by elsesiy** [comment]
@pr0gramm3r8hai Please see #164, I'll merge it as soon as it's ready..

**Comment by pr0gramm3r8hai** [comment]
@Mozharovsky  did you mean  #calendarView.refreshPresentedMonth() available on swift 1.2 too ? seems #164  is on swift 2.0, i am trying to use in swift 1.2 please make it happen ! iam on xcode Version 6.4 (6E35b)!

**Comment by elsesiy** [comment]
@pr0gramm3r8hai Swift 2 is generally speaking downward compatible but you've to use the newest Xcode release. With that you'll most likely need to convert your code as well. The README clearly states that Swift 2 is a requirement and thus it'd be way too difficult to support different language levels, sorry.
What's the problem with converting your existing project and updating Xcode??

**Comment by pr0gramm3r8hai** [comment]
@Mozharovsky : ok I am upgrading my code ! thanks for your kind response !

**Comment by pr0gramm3r8hai** [comment]
@Mozharovsky  : Refresh can be achieved on swift 1.2 (old library) by just adding some methods         "calendarView.contentController.refreshPresentedMonth()" which is available on new version of library (on swift 2.0). Cheers !

**Comment by jose920405** [comment]
@pr0gramm3r8hai
refreshPresentedMonth() is not available in my version(1.1.4)

**Comment by jose920405** [comment]
I just upgraded to version 1.2.7, and I do not find how to refresh the current month?

**Comment by msawvov** [comment]
i have version 1.2.7 too, and I can not reload the current month

**Comment by pr0gramm3r8hai** [comment]
@Mozharovsky  indeed but i did copy mothods from your new one to my old one and it is working like charm !

**Comment by elsesiy** [comment]
With the newest release 1.2.8 you should be able to use the methods mentioned for refreshing the current month...Also see #47 or #155 for reference.

**Comment by gyanaprakash** [comment]
how to show dotmark on cvcalendar
