### ISSUE TITLE
Creating calendar manually, font not updating present view

### ISSUE THREAD

**Issue by thomasbaldwinj** [Mozharovsky/CVCalendar#82]
I'm instantiating the calendarView manually, and then setting the delegates up. However, the font does not seem to be updating the presentView initially even with me setting it in the calendarAppearanceDelegate. The months after and before have the correct font set, and if I switch to another month and then switch back to the present, the view is loaded with the correct font, but not on the initial load.

Also it's worth noting that if you setup the outlets and delegates through the storyboard, it will load the correct font for the presentView initially.

P.S. I am working with the latest code from the develop branch

If you want me to fix this on my own and submit a pull request I can because I have plenty of time on my hands and am building my whole application off your calendar.

Cheers,
Thomas

**Comment by thomasbaldwinj** [comment]
I found a workaround for it. Basically you have to set the calendarAppearanceDelegate before you set the calendarDelegate because when the calendarDelegate is set, the initialLoad method gets called which creates the initial calendar with the pre-set appearance options

**Comment by Mozharovsky** [comment]
Hello @thomasbaldwinj, 

Thank you so much for figuring it out. I think it's pretty expensive to set up the whole thing more than once, so your workaround is the right way to go. I've updated the documentation regarding this feature so far. 

Regards, 
Eugene
