### ISSUE TITLE
Demo not working

### ISSUE THREAD

**Issue by baottran** [Mozharovsky/CVCalendar#85]
Hi Eugene, 

Is the demo for the calendar supposed to be working? Trying to refer to it to start but there's a number of errors in the CVCalendar folder that appears when I try to build. 

Thanks in advance,

-Bao

**Comment by martjemeyer** [comment]
Try to use the demo from the develop branch, that's the most up to date one.
https://github.com/Mozharovsky/CVCalendar/tree/develop

**Comment by baottran** [comment]
perfect! Thanks.
