### ISSUE TITLE
Demo - showing days our toggle not working

### ISSUE THREAD

**Issue by tiemevanveen** [Mozharovsky/CVCalendar#9]
Dunno if you appreciate yet another issue, but just wanted to inform you that the toggle at the bottom of your demo app is doing nothing. Both not in master nor develop. 

Tieme

**Comment by Mozharovsky** [comment]
@tiemevanveen, 

Thank you for reporting again! 

I've fixed that issue in the latest commit in **develop** branch. All you had to do was connecting an IBAction with corresponding outlet. 

Regards, 
Euegene
