### ISSUE TITLE
Show new events

### ISSUE THREAD

**Issue by Gaduris** [Mozharovsky/CVCalendar#91]
hello the library is amazing, thank you for your work, I am now implemented your library, but I have a question, I get a json from my webservices a list of days, now I want to make those days are placed in the calendar, i call "calendarView.commitCalendarViewUpdate ()", but not drawn markers, have in the function "func dotMarker (shouldShowOnDayView DayView: CVCalendarDayView)" the appropriate code in the code I read the settlement of days and compared with "dayView.date ! .day "and return true if they are equal, the problem is that this json not read when loading the viewController, we read after pressing a button, my question is how can redial event markers, I have read the wiki in the section of Delegates and says i must call this function "topMarker: shouldDisplayOnDayView" i create variable delegate and call the function but do not know what parameter should I pass,  could yuo helpme with an example? or I'm missing something? ,  in "DayView" I create a variable of type "CVCalendarDayView" and pass it, but does not work, I think I'm doing something wrong,  could  you help me please...

**Comment by martjemeyer** [comment]
Maybe you should put a piece of your code here how you compare your days. For the markers, I believe they are still only drawn when the view is loaded the first time..

**Comment by Gaduris** [comment]
Hello, this is my code, I invoke the calendar so,

viewDidLayoutSubviews override func () {
        super.viewDidLayoutSubviews ()
        
        calendarView.commitCalendarViewUpdate ()
        menuView.commitMenuViewUpdate ()
    }


In the function
dotMarker func (shouldShowOnDayView DayView: CVCalendarDayView)

var present: Boolean = false
let day = dayView.date! .day



    
            if listEventos! .count> 0 {
           
                var NUMC = listEventos! .count
                var indexC: Int

                for indexC = 0; indexC <numc; ++ IndexC {
                    
                    var data: String = listEventos [indexC]!
                    
                    TempData var [String] = dato.componentsSeparatedByString ("-")
                    
                    var datoDay: Int = TempData [0] .toInt ()!
                    
                    println ("datoDay: \ (datoDay) = \ (day)")
                    
                    if datoDay day == {
                        
                        present = true
                    }
                    
                }
                
                
            }
        


listEventos - is my arrangement with the days events




in my JSON


if (success == 1) {
                    
                    
                    let InfoData: NSArray = jsonData.valueForKey ("InfoData") ace! NSArray;
                    
                    var NUMC = InfoData.count
                    var indexC: Int
                    
                    tempArraylistEvents var = [String] (count: NUMC, repeatedValue: "")
                   
                    
                    for indexC = 0; indexC <numc; ++ IndexC {
                        
                        var dateCal: String = InfoData [indexC] .valueForKey ("DateCal") ace! String
                        
                        
                        dateSplit var [String] = dateCal.componentsSeparatedByString ("/")
                        
                        
                        
                        tempArraylistEvents [indexC] = "\ (dateSplit [0]) - \ (dateSplit [1])"
                        
                        
                        
                    }
                    
                    listEventos = tempArraylistEvents
                    
                    tieneEventos = true
                    
                    println ("tieneEventosJSON \ (tieneEventos)")
                    

                    // This is where I wish to invoke again the function of events, but i do not how
                    delegateCalendar .dotMarker (shouldShowOnDayView: <# DayView #>)?
                    
                }

**Comment by Mozharovsky** [comment]
Hello @Gaduris, @martjemeyer, 

It's rather difficult to find an issue in the provided pieces of code. I suggest you to update the library since it has been improved a lot recently. As for dot markers, you could send me a link to your project (or simply project sources) via email so I can help you set it up. 

Hope it helps. 

Regards, 
Eugene
