### ISSUE TITLE
Selecting DayView Programatically

### ISSUE THREAD

**Issue by rajavikram** [Mozharovsky/CVCalendar#99]
Hi Eugene,
I am implementing this calendar in my app, where a tableView shows the events of each day.
Looking at some other day planner apps , I thought it would be a good idea if i can change the dayView of the calendar (as the user scrolls down the tableView) to the appropriate day.

I tried to modify your implementation to do this, but am not able to. 
It would be great if you can point me in the right direction to achieve this.

**Comment by martjemeyer** [comment]
The implementation should be in your tableview, since that can hardly be added in the calendar. So if you catch the moment the calendar should switch while scrolling your tableview, just call: self.calendarView.toggleViewWithDate(newdate)

You can rewrite the extension to add month to days
